namespace PESpy
{
    public enum CorCompileSection
    {
        CORCOMPILE_SECTION_MODULE,
        CORCOMPILE_SECTION_WRITE,
        CORCOMPILE_SECTION_METHOD_PRECODE_WRITE,
        CORCOMPILE_SECTION_HOT_WRITEABLE,
        CORCOMPILE_SECTION_WRITEABLE,
        CORCOMPILE_SECTION_HOT,
        CORCOMPILE_SECTION_METHOD_PRECODE_HOT,
        CORCOMPILE_SECTION_RVA_STATICS_HOT,
        CORCOMPILE_SECTION_RVA_STATICS_COLD,
        CORCOMPILE_SECTION_WARM,
        CORCOMPILE_SECTION_READONLY_SHARED_HOT,
        CORCOMPILE_SECTION_READONLY_HOT,
        CORCOMPILE_SECTION_READONLY_WARM,
        CORCOMPILE_SECTION_READONLY_COLD,
        CORCOMPILE_SECTION_READONLY_VCHUNKS,
        CORCOMPILE_SECTION_READONLY_DICTIONARY,
        CORCOMPILE_SECTION_CLASS_COLD,
        CORCOMPILE_SECTION_CROSS_DOMAIN_INFO,
        CORCOMPILE_SECTION_METHOD_PRECODE_COLD,
        CORCOMPILE_SECTION_METHOD_PRECODE_COLD_WRITEABLE,
        CORCOMPILE_SECTION_METHOD_DESC_COLD,
        CORCOMPILE_SECTION_METHOD_DESC_COLD_WRITEABLE,
        CORCOMPILE_SECTION_MODULE_COLD,
        CORCOMPILE_SECTION_DEBUG_COLD,
        CORCOMPILE_SECTION_COMPRESSED_MAPS,

        CORCOMPILE_SECTION_COUNT
    };
}
