/************************************************************************
 * This code was generated by a tool.                                   *
 * Please do not modify this file directly - modify SymStore.tt instead *
 ************************************************************************/
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace PESpy
{
    internal abstract class SymStore
    {
        public SymStore? BackingStore { get; }

        public string Name { get; }

        protected SymStore(SymStore? backingStore, string name)
        {
            BackingStore = backingStore;
            Name = name;
        }

        //######################################
        // GetFile
        //######################################

        //SymStore EntryPoint
        public static (string? filePath, SymStoreKey? keyUsed) GetFile(
            IFile? file,
            ReadOnlySpan<char> searchPath,
            SymStoreKey key,
            SymStoreKey? altKey,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            //Construct a SymStore chain

            SymStore? store = null;

            var run = true;

            while (run)
            {
                var index = searchPath.LastIndexOf('*');

                ReadOnlySpan<char> currentPath;

                if (index == -1)
                {
                    run = false;
                    currentPath = searchPath;
                }
                else
                {
                    currentPath = searchPath.Slice(index + 1);
                    searchPath = searchPath.Slice(0, index);
                }

                if (index == searchPath.Length - 1) //It's the last character
                    throw new NotImplementedException();

                if (currentPath.StartsWith("http://".AsSpan(), StringComparison.OrdinalIgnoreCase) || currentPath.StartsWith("https://".AsSpan(), StringComparison.OrdinalIgnoreCase))
                {
                    store = new HttpSymStore(currentPath.ToString(), file, httpPolicy, store);
                }
                else
                {
                    //Assume it's some kind of filesystem path
                    store = new FileSystemSymStore(currentPath.ToString(), store);
                }
            }

            return CascadeStore(key, altKey, store, progress, cancellationToken);
        }

#if !NATIVEAOT
        public static ValueTask<(string? filePath, SymStoreKey? keyUsed)> GetFileAsync(
            IFile? file,
            ReadOnlySpan<char> searchPath,
            SymStoreKey key,
            SymStoreKey? altKey,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            //Construct a SymStore chain

            SymStore? store = null;

            var run = true;

            while (run)
            {
                var index = searchPath.LastIndexOf('*');

                ReadOnlySpan<char> currentPath;

                if (index == -1)
                {
                    run = false;
                    currentPath = searchPath;
                }
                else
                {
                    currentPath = searchPath.Slice(index + 1);
                    searchPath = searchPath.Slice(0, index);
                }

                if (index == searchPath.Length - 1) //It's the last character
                    throw new NotImplementedException();

                if (currentPath.StartsWith("http://".AsSpan(), StringComparison.OrdinalIgnoreCase) || currentPath.StartsWith("https://".AsSpan(), StringComparison.OrdinalIgnoreCase))
                {
                    store = new HttpSymStore(currentPath.ToString(), file, httpPolicy, store);
                }
                else
                {
                    //Assume it's some kind of filesystem path
                    store = new FileSystemSymStore(currentPath.ToString(), store);
                }
            }

            return CascadeStoreAsync(key, altKey, store, progress, cancellationToken);
        }
#endif

        //######################################
        // CascadeStore
        //######################################

        //Top level cascade dispatcher
        private static (string? filePath, SymStoreKey? keyUsed) CascadeStore(
            SymStoreKey key,
            SymStoreKey? altKey,
            SymStore store,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            //This method functions as the top level dispatcher for the symbol store. The first store in the chain
            //is queried to see whether it has the key we're looking for. If it has the file, it will return it
            //immediately; otherwise, it will ask its parent whether it has the file, and if so will copy the file
            //into itself

            SymStoreKey? keyUsed = null;

            var fileAndStream = store!.GetFileOrCascade(key, progress, cancellationToken);

            if (fileAndStream != null)
                keyUsed = key;
            else
            {
                if (altKey != null)
                {
                    fileAndStream = store!.GetFileOrCascade(altKey.Value, progress, cancellationToken);

                    if (fileAndStream != null)
                        keyUsed = altKey;
                }
            }

            if (fileAndStream != null)
            {
                fileAndStream.Value.stream.Dispose();
                return (fileAndStream.Value.file.FileName, keyUsed);
            }

            return default;
        }

#if !NATIVEAOT
        private static async ValueTask<(string? filePath, SymStoreKey? keyUsed)> CascadeStoreAsync(
            SymStoreKey key,
            SymStoreKey? altKey,
            SymStore store,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            //This method functions as the top level dispatcher for the symbol store. The first store in the chain
            //is queried to see whether it has the key we're looking for. If it has the file, it will return it
            //immediately; otherwise, it will ask its parent whether it has the file, and if so will copy the file
            //into itself

            SymStoreKey? keyUsed = null;

            var fileAndStream = await store!.GetFileOrCascadeAsync(key, progress, cancellationToken).ConfigureAwait(false);

            if (fileAndStream != null)
                keyUsed = key;
            else
            {
                if (altKey != null)
                {
                    fileAndStream = await store!.GetFileOrCascadeAsync(altKey.Value, progress, cancellationToken).ConfigureAwait(false);

                    if (fileAndStream != null)
                        keyUsed = altKey;
                }
            }

            if (fileAndStream != null)
            {
                fileAndStream.Value.stream.Dispose();
                return (fileAndStream.Value.file.FileName, keyUsed);
            }

            return default;
        }
#endif

        //#######################################
        // Cascade
        //#######################################

        public (SymStoreFile file, Stream stream)? GetFileOrCascade(SymStoreKey key, ILocatorProgress progress, CancellationToken cancellationToken)
        {
            //Try and get a file from a given store. If the store contains the requested file, we return it immediately.
            //Otherwise, we ask our parent store whether it has the desired file; if so, we copy it down into ourselves
            //and return the copy that was created in this store back to the caller

            var fileAndStream = GetFile(key, progress, cancellationToken);

            if (fileAndStream == null)
            {
                if (BackingStore != null)
                {
                    try
                    {
                        progress?.Notify(LocatorProgressEventArgs.CreateBeginCascadeStore(key, Name, BackingStore.Name));

                        fileAndStream = BackingStore.GetFileOrCascade(key, progress, cancellationToken);

                        if (fileAndStream != null)
                        {
                            var oldStream = fileAndStream.Value.stream;

                            try
                            {
                                progress?.Notify(LocatorProgressEventArgs.CreateCopyCascadeFile(key, Name, BackingStore.Name, (int) fileAndStream.Value.stream.Length));
                                fileAndStream = SaveFile(key, fileAndStream.Value.file, fileAndStream.Value.stream, cancellationToken);
                            }
                            finally
                            {
                                oldStream.Dispose();
                            }
                        }
                    }
                    finally
                    {
                        progress?.Notify(LocatorProgressEventArgs.CreateEndCascadeStore(key, Name, BackingStore.Name));
                    }
                }
            }

            return fileAndStream;
        }

#if !NATIVEAOT
        public async ValueTask<(SymStoreFile file, Stream stream)?> GetFileOrCascadeAsync(SymStoreKey key, ILocatorProgress progress, CancellationToken cancellationToken)
        {
            //Try and get a file from a given store. If the store contains the requested file, we return it immediately.
            //Otherwise, we ask our parent store whether it has the desired file; if so, we copy it down into ourselves
            //and return the copy that was created in this store back to the caller

            var fileAndStream = await GetFileAsync(key, progress, cancellationToken).ConfigureAwait(false);

            if (fileAndStream == null)
            {
                if (BackingStore != null)
                {
                    try
                    {
                        progress?.Notify(LocatorProgressEventArgs.CreateBeginCascadeStore(key, Name, BackingStore.Name));

                        fileAndStream = await BackingStore.GetFileOrCascadeAsync(key, progress, cancellationToken).ConfigureAwait(false);

                        if (fileAndStream != null)
                        {
                            var oldStream = fileAndStream.Value.stream;

                            try
                            {
                                progress?.Notify(LocatorProgressEventArgs.CreateCopyCascadeFile(key, Name, BackingStore.Name, (int) fileAndStream.Value.stream.Length));
                                fileAndStream = await SaveFileAsync(key, fileAndStream.Value.file, fileAndStream.Value.stream, cancellationToken).ConfigureAwait(false);
                            }
                            finally
                            {
                                oldStream.Dispose();
                            }
                        }
                    }
                    finally
                    {
                        progress?.Notify(LocatorProgressEventArgs.CreateEndCascadeStore(key, Name, BackingStore.Name));
                    }
                }
            }

            return fileAndStream;
        }
#endif

        protected abstract (SymStoreFile file, Stream stream)? GetFile(SymStoreKey key, ILocatorProgress progress, CancellationToken cancellationToken);

        protected abstract (SymStoreFile file, Stream stream)? SaveFile(SymStoreKey key, SymStoreFile file, Stream stream, CancellationToken cancellationToken);

#if !NATIVEAOT
        protected abstract ValueTask<(SymStoreFile file, Stream stream)?> GetFileAsync(SymStoreKey key, ILocatorProgress progress, CancellationToken cancellationToken);

        protected abstract ValueTask<(SymStoreFile file, Stream stream)?> SaveFileAsync(SymStoreKey key, SymStoreFile file, Stream stream, CancellationToken cancellationToken);
#endif
    }
}
