using System;

namespace PESpy
{
    [Flags]
    public enum IMAGE_DLLCHARACTERISTICS_EX
    {
        IMAGE_DLLCHARACTERISTICS_EX_CET_COMPAT = 1,
        IMAGE_DLLCHARACTERISTICS_EX_CET_COMPAT_STRICT_MODE = 2,
        IMAGE_DLLCHARACTERISTICS_EX_CET_SET_CONTEXT_IP_VALIDATION_RELAXED_MODE = 4,
        IMAGE_DLLCHARACTERISTICS_EX_CET_DYNAMIC_APIS_ALLOW_IN_PROC = 8,
        IMAGE_DLLCHARACTERISTICS_EX_CET_RESERVED_1 = 16,
        IMAGE_DLLCHARACTERISTICS_EX_CET_RESERVED_2 = 32
    }
}
