﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_access"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_access"/>
        /// </summary>
        public static bool TryGetAccess(in this TypType typType, out CV_access_e access) =>
            TryGetAccess((LfEasy) typType, out access);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_access"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_access"/>
        /// </summary>
        public static bool TryGetAccess(in this LfEasy lfEasy, out CV_access_e access)
        {
            switch (lfEasy.leaf)
            {
                //LfBClass
                case LF_BCLASS:
                case LF_BINTERFACE:
                    access = ((LfBClass) lfEasy).attr.access;
                    return true;

                //LfBClass16t
                case LF_BCLASS_16t:
                    access = ((LfBClass16t) lfEasy).attr.access;
                    return true;

                //LfEnumerate
                case LF_ENUMERATE:
                case LF_ENUMERATE_ST:
                    access = ((LfEnumerate) lfEasy).attr.access;
                    return true;

                //LfVBClass16t
                case LF_IVBCLASS_16t:
                case LF_VBCLASS_16t:
                    access = ((LfVBClass16t) lfEasy).attr.access;
                    return true;

                //LfMember
                case LF_MEMBER:
                case LF_MEMBER_ST:
                    access = ((LfMember) lfEasy).attr.access;
                    return true;

                //LfMember16t
                case LF_MEMBER_16t:
                    access = ((LfMember16t) lfEasy).attr.access;
                    return true;

                //LfMemberModify
                case LF_MEMBERMODIFY:
                case LF_MEMBERMODIFY_ST:
                    access = ((LfMemberModify) lfEasy).attr.access;
                    return true;

                //LfNestTypeEx
                case LF_NESTTYPEEX:
                case LF_NESTTYPEEX_ST:
                    access = ((LfNestTypeEx) lfEasy).attr.access;
                    return true;

                //LfOneMethod
                case LF_ONEMETHOD:
                case LF_ONEMETHOD_ST:
                    access = ((LfOneMethod) lfEasy).attr.access;
                    return true;

                //LfOneMethod16t
                case LF_ONEMETHOD_16t:
                    access = ((LfOneMethod16t) lfEasy).attr.access;
                    return true;

                //LfSTMember
                case LF_STMEMBER:
                case LF_STMEMBER_ST:
                    access = ((LfSTMember) lfEasy).attr.access;
                    return true;

                //LfSTMember16t
                case LF_STMEMBER_16t:
                    access = ((LfSTMember16t) lfEasy).attr.access;
                    return true;

                //LfVBClass
                case LF_VBCLASS:
                    access = ((LfVBClass) lfEasy).attr.access;
                    return true;
            }

            access = default;
            return false;
        }
    }
}
