﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_addressOffset"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_addressOffset"/>
        /// </summary>
        public static bool TryGetAddressOffset(in this SymType symType, out int addressOffset)
        {
            switch (symType.rectyp)
            {
                //AnnotationSym
                case S_ANNOTATION:
                    addressOffset = ((AnnotationSym) symType).off;
                    return true;

                //BlockSym16
                case S_BLOCK16:
                case S_WITH16:
                    addressOffset = ((BlockSym16) symType).off;
                    return true;

                //BlockSym32
                case S_BLOCK32:
                case S_BLOCK32_ST:
                case S_WITH32:
                case S_WITH32_ST:
                    addressOffset = ((BlockSym32) symType).off;
                    return true;

                //CExMSym16
                case S_CEXMODEL16:
                    addressOffset = ((CExMSym16) symType).off;
                    return true;

                //CExMSym32
                case S_CEXMODEL32:
                    addressOffset = ((CExMSym32) symType).off;
                    return true;

                //CoffGroupSym
                case S_COFFGROUP:
                    addressOffset = ((CoffGroupSym) symType).off;
                    return true;

                //DataSym16
                case S_GDATA16:
                case S_LDATA16:
                case S_PUB16:
                    addressOffset = ((DataSym16) symType).off;
                    return true;

                //DataSym32
                case S_GDATA32:
                case S_GDATA32_ST:
                case S_GMANDATA:
                case S_GMANDATA_ST:
                case S_GTHREAD32:
                case S_GTHREAD32_ST:
                case S_LDATA32:
                case S_LDATA32_ST:
                case S_LMANDATA:
                case S_LMANDATA_ST:
                case S_LTHREAD32:
                case S_LTHREAD32_ST:
                    addressOffset = ((DataSym32) symType).off;
                    return true;

                //DataSym3216t
                case S_GDATA32_16t:
                case S_GTHREAD32_16t:
                case S_LDATA32_16t:
                case S_LTHREAD32_16t:
                case S_PUB32_16t:
                    addressOffset = ((DataSym3216t) symType).off;
                    return true;

                //ManProcSym
                case S_GMANPROC:
                case S_GMANPROC_ST:
                case S_LMANPROC:
                case S_LMANPROC_ST:
                    addressOffset = ((ManProcSym) symType).off;
                    return true;

                //ProcSym16
                case S_GPROC16:
                case S_LPROC16:
                    addressOffset = ((ProcSym16) symType).off;
                    return true;

                //ProcSym32
                case S_GPROC32:
                case S_GPROC32_ID:
                case S_GPROC32_ST:
                case S_LPROC32:
                case S_LPROC32_DPC:
                case S_LPROC32_DPC_ID:
                case S_LPROC32_ID:
                case S_LPROC32_ST:
                    addressOffset = ((ProcSym32) symType).off;
                    return true;

                //ProcSym3216t
                case S_GPROC32_16t:
                case S_LPROC32_16t:
                    addressOffset = ((ProcSym3216t) symType).off;
                    return true;

                //ProcSymIA64
                case S_GPROCIA64:
                case S_GPROCIA64_ID:
                case S_GPROCIA64_ST:
                case S_LPROCIA64:
                case S_LPROCIA64_ID:
                case S_LPROCIA64_ST:
                    addressOffset = ((ProcSymIA64) symType).off;
                    return true;

                //ProcSymMips
                case S_GPROCMIPS:
                case S_GPROCMIPS_ID:
                case S_GPROCMIPS_ST:
                case S_LPROCMIPS:
                case S_LPROCMIPS_ID:
                case S_LPROCMIPS_ST:
                    addressOffset = ((ProcSymMips) symType).off;
                    return true;

                //ProcSymMips16t
                case S_GPROCMIPS_16t:
                case S_LPROCMIPS_16t:
                    addressOffset = ((ProcSymMips16t) symType).off;
                    return true;

                //LabelSym16
                case S_LABEL16:
                    addressOffset = ((LabelSym16) symType).off;
                    return true;

                //LabelSym32
                case S_LABEL32:
                case S_LABEL32_ST:
                    addressOffset = ((LabelSym32) symType).off;
                    return true;

                //PubSym32
                case S_PUB32:
                case S_PUB32_ST:
                    addressOffset = ((PubSym32) symType).off;
                    return true;

                //ThunkSym16
                case S_THUNK16:
                    addressOffset = ((ThunkSym16) symType).off;
                    return true;

                //ThunkSym32
                case S_THUNK32:
                case S_THUNK32_ST:
                    addressOffset = ((ThunkSym32) symType).off;
                    return true;
            }

            addressOffset = default;
            return false;
        }
    }
}
