﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_arrayIndexType"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_arrayIndexType"/>
        /// </summary>
        public static bool TryGetArrayIndexType(in this TypType typType, out TypOrEnumType arrayIndexType) =>
            TryGetArrayIndexType((LfEasy) typType, out arrayIndexType);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_arrayIndexType"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_arrayIndexType"/>
        /// </summary>
        public static bool TryGetArrayIndexType(in this LfEasy lfEasy, out TypOrEnumType arrayIndexType)
        {
            switch (lfEasy.leaf)
            {
                //LfArray
                case LF_ARRAY:
                case LF_ARRAY_ST:
                    arrayIndexType = ((LfArray) lfEasy).idxtype;
                    return true;

                //LfArray16t
                case LF_ARRAY_16t:
                    arrayIndexType = ((LfArray16t) lfEasy).idxtype;
                    return true;
            }

            arrayIndexType = default;
            return false;
        }
    }
}
