﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_backEndQFE"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_backEndQFE"/>
        /// </summary>
        public static bool TryGetBackEndQFE(in this SymType symType, out int backEndQFE)
        {
            switch (symType.rectyp)
            {
                //CompileSym3
                case S_COMPILE3:
                    backEndQFE = ((CompileSym3) symType).verQFE;
                    return true;
            }

            backEndQFE = default;
            return false;
        }
    }
}
