﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_bindSpace"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_bindSpace"/>
        /// </summary>
        public static bool TryGetBindSpace(in this SymType symType, out int bindSpace)
        {
            switch (symType.rectyp)
            {
                //DataSymHLSL32Ex
                case S_GDATA_HLSL32_EX:
                case S_LDATA_HLSL32_EX:
                    bindSpace = ((DataSymHLSL32Ex) symType).bindSpace;
                    return true;
            }

            bindSpace = default;
            return false;
        }
    }
}
