﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_bitPosition"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_bitPosition"/>
        /// </summary>
        public static bool TryGetBitPosition(in this TypType typType, out int bitPosition) =>
            TryGetBitPosition((LfEasy) typType, out bitPosition);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_bitPosition"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_bitPosition"/>
        /// </summary>
        public static bool TryGetBitPosition(in this LfEasy lfEasy, out int bitPosition)
        {
            switch (lfEasy.leaf)
            {
                //LfBitfield
                case LF_BITFIELD:
                    bitPosition = ((LfBitfield) lfEasy).position;
                    return true;

                //LfBitfield16t
                case LF_BITFIELD_16t:
                    bitPosition = ((LfBitfield16t) lfEasy).position;
                    return true;
            }

            bitPosition = default;
            return false;
        }
    }
}
