﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_builtInKind"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_builtInKind"/>
        /// </summary>
        public static bool TryGetBuiltInKind(in this TypType typType, out int builtInKind) =>
            TryGetBuiltInKind((LfEasy) typType, out builtInKind);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_builtInKind"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_builtInKind"/>
        /// </summary>
        public static bool TryGetBuiltInKind(in this LfEasy lfEasy, out int builtInKind)
        {
            switch (lfEasy.leaf)
            {
                //LfHLSL
                case LF_HLSL:
                    builtInKind = ((LfHLSL) lfEasy).kind;
                    return true;
            }

            builtInKind = default;
            return false;
        }
    }
}
