﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_characteristics"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_characteristics"/>
        /// </summary>
        public static bool TryGetCharacteristics(in this SymType symType, out IMAGE_SCN characteristics)
        {
            switch (symType.rectyp)
            {
                //CoffGroupSym
                case S_COFFGROUP:
                    characteristics = ((CoffGroupSym) symType).characteristics;
                    return true;

                //SectionSym
                case S_SECTION:
                    characteristics = ((SectionSym) symType).characteristics;
                    return true;
            }

            characteristics = default;
            return false;
        }
    }
}
