﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_classParent"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_classParent"/>
        /// </summary>
        public static bool TryGetClassParent(in this TypType typType, out TypOrEnumType classParent) =>
            TryGetClassParent((LfEasy) typType, out classParent);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_classParent"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_classParent"/>
        /// </summary>
        public static bool TryGetClassParent(in this LfEasy lfEasy, out TypOrEnumType classParent)
        {
            switch (lfEasy.leaf)
            {
                //LfMFuncId
                case LF_MFUNC_ID:
                    classParent = ((LfMFuncId) lfEasy).parentType;
                    return true;
            }

            classParent = default;
            return false;
        }
    }
}
