﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_compilerGenerated"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_compilerGenerated"/>
        /// </summary>
        public static bool TryGetCompilerGenerated(in this TypType typType, out bool compilerGenerated)
        {
            switch (typType.leaf)
            {
                //LfBClass
                case LF_BCLASS:
                case LF_BINTERFACE:
                    compilerGenerated = ((LfBClass) typType).attr.compgenx;
                    return true;

                //LfBClass16t
                case LF_BCLASS_16t:
                    compilerGenerated = ((LfBClass16t) typType).attr.compgenx;
                    return true;

                //LfEnumerate
                case LF_ENUMERATE:
                case LF_ENUMERATE_ST:
                    compilerGenerated = ((LfEnumerate) typType).attr.compgenx;
                    return true;

                //LfVBClass16t
                case LF_IVBCLASS_16t:
                case LF_VBCLASS_16t:
                    compilerGenerated = ((LfVBClass16t) typType).attr.compgenx;
                    return true;

                //LfMember
                case LF_MEMBER:
                case LF_MEMBER_ST:
                    compilerGenerated = ((LfMember) typType).attr.compgenx;
                    return true;

                //LfMember16t
                case LF_MEMBER_16t:
                    compilerGenerated = ((LfMember16t) typType).attr.compgenx;
                    return true;

                //LfMemberModify
                case LF_MEMBERMODIFY:
                case LF_MEMBERMODIFY_ST:
                    compilerGenerated = ((LfMemberModify) typType).attr.compgenx;
                    return true;

                //LfNestTypeEx
                case LF_NESTTYPEEX:
                case LF_NESTTYPEEX_ST:
                    compilerGenerated = ((LfNestTypeEx) typType).attr.compgenx;
                    return true;

                //LfOneMethod
                case LF_ONEMETHOD:
                case LF_ONEMETHOD_ST:
                    compilerGenerated = ((LfOneMethod) typType).attr.compgenx;
                    return true;

                //LfOneMethod16t
                case LF_ONEMETHOD_16t:
                    compilerGenerated = ((LfOneMethod16t) typType).attr.compgenx;
                    return true;

                //LfSTMember
                case LF_STMEMBER:
                case LF_STMEMBER_ST:
                    compilerGenerated = ((LfSTMember) typType).attr.compgenx;
                    return true;

                //LfSTMember16t
                case LF_STMEMBER_16t:
                    compilerGenerated = ((LfSTMember16t) typType).attr.compgenx;
                    return true;

                //LfVBClass
                case LF_VBCLASS:
                    compilerGenerated = ((LfVBClass) typType).attr.compgenx;
                    return true;
            }

            compilerGenerated = default;
            return false;
        }
    }
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_compilerGenerated"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_compilerGenerated"/>
        /// </summary>
        public static bool TryGetCompilerGenerated(in this SymType symType, out bool compilerGenerated)
        {
            switch (symType.rectyp)
            {
                //FileStaticSym
                case S_FILESTATIC:
                    compilerGenerated = ((FileStaticSym) symType).flags.fCompGenx;
                    return true;

                //LocalSym
                case S_LOCAL:
                    compilerGenerated = ((LocalSym) symType).flags.fCompGenx;
                    return true;

                //LocalDPCGroupSharedSym
                case S_LOCAL_DPC_GROUPSHARED:
                    compilerGenerated = ((LocalDPCGroupSharedSym) symType).flags.fCompGenx;
                    return true;
            }

            compilerGenerated = default;
            return false;
        }
    }
}
