﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_constructor"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_constructor"/>
        /// </summary>
        public static bool TryGetConstructor(in this TypType typType, out bool constructor)
        {
            switch (typType.leaf)
            {
                //LfClass
                case LF_CLASS:
                case LF_CLASS_ST:
                case LF_INTERFACE:
                case LF_STRUCTURE:
                case LF_STRUCTURE_ST:
                    constructor = ((LfClass) typType).property.ctor;
                    return true;

                //LfClass16t
                case LF_CLASS_16t:
                case LF_STRUCTURE_16t:
                    constructor = ((LfClass16t) typType).property.ctor;
                    return true;

                //LfEnum
                case LF_ENUM:
                case LF_ENUM_ST:
                    constructor = ((LfEnum) typType).property.ctor;
                    return true;

                //LfEnum16t
                case LF_ENUM_16t:
                    constructor = ((LfEnum16t) typType).property.ctor;
                    return true;

                //LfMFunc
                case LF_MFUNCTION:
                    constructor = ((LfMFunc) typType).funcattr.ctor;
                    return true;

                //LfMFunc16t
                case LF_MFUNCTION_16t:
                    constructor = ((LfMFunc16t) typType).funcattr.ctor;
                    return true;

                //LfProc
                case LF_PROCEDURE:
                    constructor = ((LfProc) typType).funcattr.ctor;
                    return true;

                //LfProc16t
                case LF_PROCEDURE_16t:
                    constructor = ((LfProc16t) typType).funcattr.ctor;
                    return true;

                //LfUnion
                case LF_UNION:
                case LF_UNION_ST:
                    constructor = ((LfUnion) typType).property.ctor;
                    return true;

                //LfUnion16t
                case LF_UNION_16t:
                    constructor = ((LfUnion16t) typType).property.ctor;
                    return true;
            }

            constructor = default;
            return false;
        }
    }
}
