﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_editAndContinueEnabled"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_editAndContinueEnabled"/>
        /// </summary>
        public static bool TryGetEditAndContinueEnabled(in this SymType symType, out bool editAndContinueEnabled)
        {
            switch (symType.rectyp)
            {
                //CompileSym
                case S_COMPILE2:
                case S_COMPILE2_ST:
                    editAndContinueEnabled = ((CompileSym) symType).fEC;
                    return true;

                //CompileSym3
                case S_COMPILE3:
                    editAndContinueEnabled = ((CompileSym3) symType).fEC;
                    return true;
            }

            editAndContinueEnabled = default;
            return false;
        }
    }
}
