﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_exceptionHandlerAddressSection"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_exceptionHandlerAddressSection"/>
        /// </summary>
        public static bool TryGetExceptionHandlerAddressSection(in this SymType symType, out int exceptionHandlerAddressSection, ICodeViewModuleAccessor? codeViewModuleAccessor = null)
        {
            switch (symType.rectyp)
            {
                //FrameProcSym
                case S_FRAMEPROC:
                    exceptionHandlerAddressSection = ((FrameProcSym) symType).sectExHdlr;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_FRAMEPROC, out var child, codeViewModuleAccessor))
                    {
                        exceptionHandlerAddressSection = ((FrameProcSym) child).sectExHdlr;
                        return true;
                    }

                    break;
            }

            exceptionHandlerAddressSection = default;
            return false;
        }
    }
}
