﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_farReturn"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_farReturn"/>
        /// </summary>
        public static bool TryGetFarReturn(in this SymType symType, out bool farReturn)
        {
            switch (symType.rectyp)
            {
                //ManProcSym
                case S_GMANPROC:
                case S_GMANPROC_ST:
                case S_LMANPROC:
                case S_LMANPROC_ST:
                    farReturn = ((ManProcSym) symType).flags.CV_PFLAG_FAR;
                    return true;

                //ProcSym16
                case S_GPROC16:
                case S_LPROC16:
                    farReturn = ((ProcSym16) symType).flags.CV_PFLAG_FAR;
                    return true;

                //ProcSym32
                case S_GPROC32:
                case S_GPROC32_ID:
                case S_GPROC32_ST:
                case S_LPROC32:
                case S_LPROC32_DPC:
                case S_LPROC32_DPC_ID:
                case S_LPROC32_ID:
                case S_LPROC32_ST:
                    farReturn = ((ProcSym32) symType).flags.CV_PFLAG_FAR;
                    return true;

                //ProcSym3216t
                case S_GPROC32_16t:
                case S_LPROC32_16t:
                    farReturn = ((ProcSym3216t) symType).flags.CV_PFLAG_FAR;
                    return true;

                //ProcSymIA64
                case S_GPROCIA64:
                case S_GPROCIA64_ID:
                case S_GPROCIA64_ST:
                case S_LPROCIA64:
                case S_LPROCIA64_ID:
                case S_LPROCIA64_ST:
                    farReturn = ((ProcSymIA64) symType).flags.CV_PFLAG_FAR;
                    return true;

                //LabelSym16
                case S_LABEL16:
                    farReturn = ((LabelSym16) symType).flags.CV_PFLAG_FAR;
                    return true;

                //LabelSym32
                case S_LABEL32:
                case S_LABEL32_ST:
                    farReturn = ((LabelSym32) symType).flags.CV_PFLAG_FAR;
                    return true;
            }

            farReturn = default;
            return false;
        }
    }
}
