﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_finalLiveStaticSize"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_finalLiveStaticSize"/>
        /// </summary>
        public static bool TryGetFinalLiveStaticSize(in this SymType symType, out int finalLiveStaticSize, ICodeViewModuleAccessor? codeViewModuleAccessor = null)
        {
            switch (symType.rectyp)
            {
                //PogoInfo
                case S_POGODATA:
                    finalLiveStaticSize = ((PogoInfo) symType).staInstLive;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_POGODATA, out var child, codeViewModuleAccessor))
                    {
                        finalLiveStaticSize = ((PogoInfo) child).staInstLive;
                        return true;
                    }

                    break;
            }

            finalLiveStaticSize = default;
            return false;
        }
    }
}
