﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol9.get_framePadSize"/><para/>
        /// Corresponds to <see cref="IDiaSymbol9.get_framePadSize"/>
        /// </summary>
        public static bool TryGetFramePadSize(in this SymType symType, out int framePadSize)
        {
            switch (symType.rectyp)
            {
                //FrameProcSym
                case S_FRAMEPROC:
                    framePadSize = ((FrameProcSym) symType).cbPad;
                    return true;
            }

            framePadSize = default;
            return false;
        }
    }
}
