﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol9.get_framePadOffset"/><para/>
        /// Corresponds to <see cref="IDiaSymbol9.get_framePadOffset"/>
        /// </summary>
        public static bool TryGetFramePadOffset(in this SymType symType, out int framePadOffset)
        {
            switch (symType.rectyp)
            {
                //FrameProcSym
                case S_FRAMEPROC:
                    framePadOffset = ((FrameProcSym) symType).offPad;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_FRAMEPROC, out var child))
                    {
                        framePadOffset = ((FrameProcSym) child).offPad;
                        return true;
                    }

                    break;
            }

            framePadOffset = default;
            return false;
        }
    }
}
