﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_frontEndMinor"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_frontEndMinor"/>
        /// </summary>
        public static bool TryGetFrontEndMinor(in this SymType symType, out int frontEndMinor)
        {
            switch (symType.rectyp)
            {
                //CompileSym
                case S_COMPILE2:
                case S_COMPILE2_ST:
                    frontEndMinor = ((CompileSym) symType).verFEMinor;
                    return true;

                //CompileSym3
                case S_COMPILE3:
                    frontEndMinor = ((CompileSym3) symType).verFEMinor;
                    return true;
            }

            frontEndMinor = default;
            return false;
        }
    }
}
