﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_hasControlFlowCheck"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_hasControlFlowCheck"/>
        /// </summary>
        public static bool TryGetHasControlFlowCheck(in this SymType symType, out bool hasControlFlowCheck)
        {
            switch (symType.rectyp)
            {
                //FrameProcSym
                case S_FRAMEPROC:
                    hasControlFlowCheck = ((FrameProcSym) symType).fGuardCF;
                    return true;
            }

            hasControlFlowCheck = default;
            return false;
        }
    }
}
