﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_hasEHa"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_hasEHa"/>
        /// </summary>
        public static bool TryGetHasEHa(in this SymType symType, out bool hasEHa)
        {
            switch (symType.rectyp)
            {
                //FrameProcSym
                case S_FRAMEPROC:
                    hasEHa = ((FrameProcSym) symType).fAsyncEH;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_FRAMEPROC, out var child))
                    {
                        hasEHa = ((FrameProcSym) child).fAsyncEH;
                        return true;
                    }

                    break;
            }

            hasEHa = default;
            return false;
        }
    }
}
