﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_hasNestedTypes"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_hasNestedTypes"/>
        /// </summary>
        public static bool TryGetHasNestedTypes(in this TypType typType, out bool hasNestedTypes) =>
            TryGetHasNestedTypes((LfEasy) typType, out hasNestedTypes);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_hasNestedTypes"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_hasNestedTypes"/>
        /// </summary>
        public static bool TryGetHasNestedTypes(in this LfEasy lfEasy, out bool hasNestedTypes)
        {
            switch (lfEasy.leaf)
            {
                //LfClass
                case LF_CLASS:
                case LF_CLASS_ST:
                case LF_INTERFACE:
                case LF_STRUCTURE:
                case LF_STRUCTURE_ST:
                    hasNestedTypes = ((LfClass) lfEasy).property.cnested;
                    return true;

                //LfClass16t
                case LF_CLASS_16t:
                case LF_STRUCTURE_16t:
                    hasNestedTypes = ((LfClass16t) lfEasy).property.cnested;
                    return true;

                //LfEnum
                case LF_ENUM:
                case LF_ENUM_ST:
                    hasNestedTypes = ((LfEnum) lfEasy).property.cnested;
                    return true;

                //LfEnum16t
                case LF_ENUM_16t:
                    hasNestedTypes = ((LfEnum16t) lfEasy).property.cnested;
                    return true;

                //LfUnion
                case LF_UNION:
                case LF_UNION_ST:
                    hasNestedTypes = ((LfUnion) lfEasy).property.cnested;
                    return true;

                //LfUnion16t
                case LF_UNION_16t:
                    hasNestedTypes = ((LfUnion16t) lfEasy).property.cnested;
                    return true;
            }

            hasNestedTypes = default;
            return false;
        }
    }
}
