﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_hasSecurityChecks"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_hasSecurityChecks"/>
        /// </summary>
        public static bool TryGetHasSecurityChecks(in this SymType symType, out bool hasSecurityChecks, ICodeViewModuleAccessor? codeViewModuleAccessor = null)
        {
            switch (symType.rectyp)
            {
                //CompileSym
                case S_COMPILE2:
                case S_COMPILE2_ST:
                    hasSecurityChecks = ((CompileSym) symType).fSecurityChecks;
                    return true;

                //CompileSym3
                case S_COMPILE3:
                    hasSecurityChecks = ((CompileSym3) symType).fSecurityChecks;
                    return true;

                //FrameProcSym
                case S_FRAMEPROC:
                    hasSecurityChecks = ((FrameProcSym) symType).fSecurityChecks;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_FRAMEPROC, out var child, codeViewModuleAccessor))
                    {
                        hasSecurityChecks = ((FrameProcSym) child).fSecurityChecks;
                        return true;
                    }

                    break;
            }

            hasSecurityChecks = default;
            return false;
        }
    }
}
