﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_hfaFloat"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_hfaFloat"/>
        /// </summary>
        public static bool TryGetHfaFloat(in this TypType typType, out bool hfaFloat)
        {
            switch (typType.leaf)
            {
                //LfClass
                case LF_CLASS:
                case LF_CLASS_ST:
                case LF_INTERFACE:
                case LF_STRUCTURE:
                case LF_STRUCTURE_ST:
                    hfaFloat = ((LfClass) typType).property.hfa == CV_HFA_e.CV_HFA_float;
                    return true;

                //LfClass16t
                case LF_CLASS_16t:
                case LF_STRUCTURE_16t:
                    hfaFloat = ((LfClass16t) typType).property.hfa == CV_HFA_e.CV_HFA_float;
                    return true;

                //LfEnum
                case LF_ENUM:
                case LF_ENUM_ST:
                    hfaFloat = ((LfEnum) typType).property.hfa == CV_HFA_e.CV_HFA_float;
                    return true;

                //LfEnum16t
                case LF_ENUM_16t:
                    hfaFloat = ((LfEnum16t) typType).property.hfa == CV_HFA_e.CV_HFA_float;
                    return true;

                //LfUnion
                case LF_UNION:
                case LF_UNION_ST:
                    hfaFloat = ((LfUnion) typType).property.hfa == CV_HFA_e.CV_HFA_float;
                    return true;

                //LfUnion16t
                case LF_UNION_16t:
                    hfaFloat = ((LfUnion16t) typType).property.hfa == CV_HFA_e.CV_HFA_float;
                    return true;
            }

            hfaFloat = default;
            return false;
        }
    }
}
