﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isAggregated"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isAggregated"/>
        /// </summary>
        public static bool TryGetIsAggregated(in this SymType symType, out bool isAggregated)
        {
            switch (symType.rectyp)
            {
                //FileStaticSym
                case S_FILESTATIC:
                    isAggregated = ((FileStaticSym) symType).flags.fIsAggregate;
                    return true;

                //LocalSym
                case S_LOCAL:
                    isAggregated = ((LocalSym) symType).flags.fIsAggregate;
                    return true;

                //LocalDPCGroupSharedSym
                case S_LOCAL_DPC_GROUPSHARED:
                    isAggregated = ((LocalDPCGroupSharedSym) symType).flags.fIsAggregate;
                    return true;
            }

            isAggregated = default;
            return false;
        }
    }
}
