﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isConstructorVirtualBase"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isConstructorVirtualBase"/>
        /// </summary>
        public static bool TryGetIsConstructorVirtualBase(in this TypType typType, out bool isConstructorVirtualBase)
        {
            switch (typType.leaf)
            {
                //LfMFunc
                case LF_MFUNCTION:
                    isConstructorVirtualBase = ((LfMFunc) typType).funcattr.ctorvbase;
                    return true;

                //LfMFunc16t
                case LF_MFUNCTION_16t:
                    isConstructorVirtualBase = ((LfMFunc16t) typType).funcattr.ctorvbase;
                    return true;

                //LfProc
                case LF_PROCEDURE:
                    isConstructorVirtualBase = ((LfProc) typType).funcattr.ctorvbase;
                    return true;

                //LfProc16t
                case LF_PROCEDURE_16t:
                    isConstructorVirtualBase = ((LfProc16t) typType).funcattr.ctorvbase;
                    return true;
            }

            isConstructorVirtualBase = default;
            return false;
        }
    }
}
