﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isCxxReturnUdt"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isCxxReturnUdt"/>
        /// </summary>
        public static bool TryGetIsCxxReturnUdt(in this TypType typType, out bool isCxxReturnUdt) =>
            TryGetIsCxxReturnUdt((LfEasy) typType, out isCxxReturnUdt);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isCxxReturnUdt"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isCxxReturnUdt"/>
        /// </summary>
        public static bool TryGetIsCxxReturnUdt(in this LfEasy lfEasy, out bool isCxxReturnUdt)
        {
            switch (lfEasy.leaf)
            {
                //LfMFunc
                case LF_MFUNCTION:
                    isCxxReturnUdt = ((LfMFunc) lfEasy).funcattr.cxxreturnudt;
                    return true;

                //LfMFunc16t
                case LF_MFUNCTION_16t:
                    isCxxReturnUdt = ((LfMFunc16t) lfEasy).funcattr.cxxreturnudt;
                    return true;

                //LfProc
                case LF_PROCEDURE:
                    isCxxReturnUdt = ((LfProc) lfEasy).funcattr.cxxreturnudt;
                    return true;

                //LfProc16t
                case LF_PROCEDURE_16t:
                    isCxxReturnUdt = ((LfProc16t) lfEasy).funcattr.cxxreturnudt;
                    return true;
            }

            isCxxReturnUdt = default;
            return false;
        }
    }
}
