﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isDataAligned"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isDataAligned"/>
        /// </summary>
        public static bool TryGetIsDataAligned(in this SymType symType, out bool isDataAligned)
        {
            switch (symType.rectyp)
            {
                //CompileSym
                case S_COMPILE2:
                case S_COMPILE2_ST:
                    isDataAligned = !((CompileSym) symType).fNoDataAlign;
                    return true;

                //CompileSym3
                case S_COMPILE3:
                    isDataAligned = !((CompileSym3) symType).fNoDataAlign;
                    return true;
            }

            isDataAligned = default;
            return false;
        }
    }
}
