﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isLTCG"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isLTCG"/>
        /// </summary>
        public static bool TryGetIsLTCG(in this SymType symType, out bool isLTCG)
        {
            switch (symType.rectyp)
            {
                //CompileSym
                case S_COMPILE2:
                case S_COMPILE2_ST:
                    isLTCG = ((CompileSym) symType).fLTCG;
                    return true;

                //CompileSym3
                case S_COMPILE3:
                    isLTCG = ((CompileSym3) symType).fLTCG;
                    return true;
            }

            isLTCG = default;
            return false;
        }
    }
}
