﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isMatrixRowMajor"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isMatrixRowMajor"/>
        /// </summary>
        public static bool TryGetIsMatrixRowMajor(in this TypType typType, out bool isMatrixRowMajor) =>
            TryGetIsMatrixRowMajor((LfEasy) typType, out isMatrixRowMajor);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isMatrixRowMajor"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isMatrixRowMajor"/>
        /// </summary>
        public static bool TryGetIsMatrixRowMajor(in this LfEasy lfEasy, out bool isMatrixRowMajor)
        {
            switch (lfEasy.leaf)
            {
                //LfMatrix
                case LF_MATRIX:
                    isMatrixRowMajor = ((LfMatrix) lfEasy).matattr.row_major;
                    return true;
            }

            isMatrixRowMajor = default;
            return false;
        }
    }
}
