﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isPGO"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isPGO"/>
        /// </summary>
        public static bool TryGetIsPGO(in this SymType symType, out bool isPGO)
        {
            switch (symType.rectyp)
            {
                //CompileSym3
                case S_COMPILE3:
                    isPGO = ((CompileSym3) symType).fPGO;
                    return true;

                //FrameProcSym
                case S_FRAMEPROC:
                    isPGO = ((FrameProcSym) symType).fPogoOn;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_FRAMEPROC, out var child))
                    {
                        isPGO = ((FrameProcSym) child).fPogoOn;
                        return true;
                    }

                    break;
            }

            isPGO = default;
            return false;
        }
    }
}
