﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isReturnValue"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isReturnValue"/>
        /// </summary>
        public static bool TryGetIsReturnValue(in this SymType symType, out bool isReturnValue)
        {
            switch (symType.rectyp)
            {
                //FileStaticSym
                case S_FILESTATIC:
                    isReturnValue = ((FileStaticSym) symType).flags.fIsRetValue;
                    return true;

                //LocalSym
                case S_LOCAL:
                    isReturnValue = ((LocalSym) symType).flags.fIsRetValue;
                    return true;

                //LocalDPCGroupSharedSym
                case S_LOCAL_DPC_GROUPSHARED:
                    isReturnValue = ((LocalDPCGroupSharedSym) symType).flags.fIsRetValue;
                    return true;
            }

            isReturnValue = default;
            return false;
        }
    }
}
