﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_isSdl"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_isSdl"/>
        /// </summary>
        public static bool TryGetIsSdl(in this SymType symType, out bool isSdl)
        {
            switch (symType.rectyp)
            {
                //CompileSym3
                case S_COMPILE3:
                    isSdl = ((CompileSym3) symType).fSdl;
                    return true;
            }

            isSdl = default;
            return false;
        }
    }
}
