﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_language"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_language"/>
        /// </summary>
        public static bool TryGetLanguage(in this SymType symType, out CV_CFL_LANG language)
        {
            switch (symType.rectyp)
            {
                //CFlagSym
                case S_COMPILE:
                    language = ((CFlagSym) symType).language;
                    return true;

                //CompileSym
                case S_COMPILE2:
                case S_COMPILE2_ST:
                    language = ((CompileSym) symType).iLanguage;
                    return true;

                //CompileSym3
                case S_COMPILE3:
                    language = ((CompileSym3) symType).iLanguage;
                    return true;
            }

            language = default;
            return false;
        }
    }
}
