﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_msil"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_msil"/>
        /// </summary>
        public static bool TryGetMsil(in this SymType symType, out bool msil)
        {
            switch (symType.rectyp)
            {
                //PubSym32
                case S_PUB32:
                case S_PUB32_ST:
                    msil = ((PubSym32) symType).pubsymflags.fMSIL;
                    return true;
            }

            msil = default;
            return false;
        }
    }
}
