﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_noNameExport"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_noNameExport"/>
        /// </summary>
        public static bool TryGetNoNameExport(in this SymType symType, out bool noNameExport)
        {
            switch (symType.rectyp)
            {
                //ExportSym
                case S_EXPORT:
                    noNameExport = ((ExportSym) symType).fNoName;
                    return true;
            }

            noNameExport = default;
            return false;
        }
    }
}
