﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.LEAF_ENUM_e;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class TypTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_offset"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_offset"/>
        /// </summary>
        public static bool TryGetOffset(in this TypType typType, out int offset) =>
            TryGetOffset((LfEasy) typType, out offset);

        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_offset"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_offset"/>
        /// </summary>
        public static bool TryGetOffset(in this LfEasy lfEasy, out int offset)
        {
            switch (lfEasy.leaf)
            {
                //LfBClass
                case LF_BCLASS:
                case LF_BINTERFACE:
                    offset = (int) ((LfBClass) lfEasy).offset;
                    return true;

                //LfBClass16t
                case LF_BCLASS_16t:
                    offset = (int) ((LfBClass16t) lfEasy).offset;
                    return true;

                //LfVBClass16t
                case LF_IVBCLASS_16t:
                case LF_VBCLASS_16t:
                    offset = (int) ((LfVBClass16t) lfEasy).offset;
                    return true;

                //LfMember
                case LF_MEMBER:
                case LF_MEMBER_ST:
                    offset = (int) ((LfMember) lfEasy).offset;
                    return true;

                //LfMember16t
                case LF_MEMBER_16t:
                    offset = (int) ((LfMember16t) lfEasy).offset;
                    return true;

                //LfVBClass
                case LF_VBCLASS:
                    offset = (int) ((LfVBClass) lfEasy).offset;
                    return true;

                //LfVFuncOff
                case LF_VFUNCOFF:
                    offset = (int) ((LfVFuncOff) lfEasy).offset;
                    return true;

                //LfVFuncOff16t
                case LF_VFUNCOFF_16t:
                    offset = (int) ((LfVFuncOff16t) lfEasy).offset;
                    return true;
            }

            offset = default;
            return false;
        }
    }

    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_offset"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_offset"/>
        /// </summary>
        public static bool TryGetOffset(in this SymType symType, out int offset)
        {
            switch (symType.rectyp)
            {
                //FrameRelSym
                case S_ATTR_FRAMEREL:
                case S_MANFRAMEREL:
                    offset = ((FrameRelSym) symType).off;
                    return true;

                //AttrRegRel
                case S_ATTR_REGREL:
                case S_MANREGREL:
                    offset = ((AttrRegRel) symType).off;
                    return true;

                //BPRelSym16
                case S_BPREL16:
                    offset = ((BPRelSym16) symType).off;
                    return true;

                //BPRelSym32
                case S_BPREL32:
                case S_BPREL32_ST:
                    offset = ((BPRelSym32) symType).off;
                    return true;

                //BPRelSym3216t
                case S_BPREL32_16t:
                    offset = ((BPRelSym3216t) symType).off;
                    return true;

                //DefRangeSymFramePointerRel
                case S_DEFRANGE_FRAMEPOINTER_REL:
                    offset = ((DefRangeSymFramePointerRel) symType).offFramePointer;
                    return true;

                //DefRangeSymFramePointerRelFullScope
                case S_DEFRANGE_FRAMEPOINTER_REL_FULL_SCOPE:
                    offset = ((DefRangeSymFramePointerRelFullScope) symType).offFramePointer;
                    return true;

                //RegRel16
                case S_REGREL16:
                    offset = ((RegRel16) symType).off;
                    return true;

                //RegRel32
                case S_REGREL32:
                case S_REGREL32_ENCTMP:
                case S_REGREL32_ST:
                    offset = ((RegRel32) symType).off;
                    return true;

                //RegRel3216t
                case S_REGREL32_16t:
                    offset = ((RegRel3216t) symType).off;
                    return true;
            }

            offset = default;
            return false;
        }
    }
}
