﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_offset"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_offset"/>
        /// </summary>
        public static bool TryGetOffset(in this SymType symType, out int offset)
        {
            switch (symType.rectyp)
            {
                //FrameRelSym
                case S_ATTR_FRAMEREL:
                case S_MANFRAMEREL:
                    offset = ((FrameRelSym) symType).off;
                    return true;

                //AttrRegRel
                case S_ATTR_REGREL:
                case S_MANREGREL:
                    offset = ((AttrRegRel) symType).off;
                    return true;

                //BPRelSym16
                case S_BPREL16:
                    offset = ((BPRelSym16) symType).off;
                    return true;

                //BPRelSym32
                case S_BPREL32:
                case S_BPREL32_ST:
                    offset = ((BPRelSym32) symType).off;
                    return true;

                //BPRelSym3216t
                case S_BPREL32_16t:
                    offset = ((BPRelSym3216t) symType).off;
                    return true;

                //DefRangeSymFramePointerRel
                case S_DEFRANGE_FRAMEPOINTER_REL:
                    offset = ((DefRangeSymFramePointerRel) symType).offFramePointer;
                    return true;

                //DefRangeSymFramePointerRelFullScope
                case S_DEFRANGE_FRAMEPOINTER_REL_FULL_SCOPE:
                    offset = ((DefRangeSymFramePointerRelFullScope) symType).offFramePointer;
                    return true;

                //RegRel16
                case S_REGREL16:
                    offset = ((RegRel16) symType).off;
                    return true;

                //RegRel32
                case S_REGREL32:
                case S_REGREL32_ENCTMP:
                case S_REGREL32_ST:
                    offset = ((RegRel32) symType).off;
                    return true;

                //RegRel3216t
                case S_REGREL32_16t:
                    offset = ((RegRel3216t) symType).off;
                    return true;
            }

            offset = default;
            return false;
        }
    }
}
