﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_PGODynamicInstructionCount"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_PGODynamicInstructionCount"/>
        /// </summary>
        public static bool TryGetPGODynamicInstructionCount(in this SymType symType, out long PGODynamicInstructionCount)
        {
            switch (symType.rectyp)
            {
                //PogoInfo
                case S_POGODATA:
                    PGODynamicInstructionCount = ((PogoInfo) symType).dynCount;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_POGODATA, out var child))
                    {
                        PGODynamicInstructionCount = ((PogoInfo) child).dynCount;
                        return true;
                    }

                    break;
            }

            PGODynamicInstructionCount = default;
            return false;
        }
    }
}
