﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_PGOEntryCount"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_PGOEntryCount"/>
        /// </summary>
        public static bool TryGetPGOEntryCount(in this SymType symType, out int PGOEntryCount, ICodeViewModuleAccessor? codeViewModuleAccessor = null)
        {
            switch (symType.rectyp)
            {
                //PogoInfo
                case S_POGODATA:
                    PGOEntryCount = ((PogoInfo) symType).invocations;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_POGODATA, out var child, codeViewModuleAccessor))
                    {
                        PGOEntryCount = ((PogoInfo) child).invocations;
                        return true;
                    }

                    break;
            }

            PGOEntryCount = default;
            return false;
        }
    }
}
