﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_registerId"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_registerId"/>
        /// </summary>
        public static bool TryGetRegisterId(in this SymType symType, out CV_HREG_e registerId)
        {
            switch (symType.rectyp)
            {
                //AttrRegSym
                case S_ATTR_REGISTER:
                case S_MANREGISTER:
                case S_MANREGISTER_ST:
                    registerId = ((AttrRegSym) symType).reg;
                    return true;

                //AttrRegRel
                case S_ATTR_REGREL:
                case S_MANREGREL:
                case S_MANREGREL_ST:
                    registerId = ((AttrRegRel) symType).reg;
                    return true;

                //DefRangeSymRegister
                case S_DEFRANGE_REGISTER:
                    registerId = ((DefRangeSymRegister) symType).reg;
                    return true;

                //DefRangeSymSubfieldRegister
                case S_DEFRANGE_SUBFIELD_REGISTER:
                    registerId = ((DefRangeSymSubfieldRegister) symType).reg;
                    return true;

                //FrameCookie
                case S_FRAMECOOKIE:
                    registerId = ((FrameCookie) symType).reg;
                    return true;

                //RegSym
                case S_REGISTER:
                case S_REGISTER_ST:
                    registerId = ((RegSym) symType).reg;
                    return true;

                //RegSym16t
                case S_REGISTER_16t:
                    registerId = ((RegSym16t) symType).reg;
                    return true;

                //RegRel16
                case S_REGREL16:
                    registerId = ((RegRel16) symType).reg;
                    return true;

                //RegRel32
                case S_REGREL32:
                case S_REGREL32_ST:
                    registerId = ((RegRel32) symType).reg;
                    return true;

                //RegRel3216t
                case S_REGREL32_16t:
                    registerId = ((RegRel3216t) symType).reg;
                    return true;

                //SLink32
                case S_SLINK32:
                    registerId = ((SLink32) symType).reg;
                    return true;
            }

            registerId = default;
            return false;
        }
    }
}
