﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_registerType"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_registerType"/>
        /// </summary>
        public static bool TryGetRegisterType(in this SymType symType, out CV_HLSLREG_e registerType)
        {
            switch (symType.rectyp)
            {
                //DefRangeSymHLSL
                case S_DEFRANGE_DPC_PTR_TAG:
                case S_DEFRANGE_HLSL:
                    registerType = ((DefRangeSymHLSL) symType).regType;
                    return true;

                //DataSymHLSL
                case S_GDATA_HLSL:
                case S_LDATA_HLSL:
                    registerType = ((DataSymHLSL) symType).regType;
                    return true;

                //DataSymHLSL32Ex
                case S_GDATA_HLSL32_EX:
                case S_LDATA_HLSL32_EX:
                    registerType = ((DataSymHLSL32Ex) symType).regType;
                    return true;
            }

            registerType = default;
            return false;
        }
    }
}
