﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_staticSize"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_staticSize"/>
        /// </summary>
        public static bool TryGetStaticSize(in this SymType symType, out int staticSize)
        {
            switch (symType.rectyp)
            {
                //PogoInfo
                case S_POGODATA:
                    staticSize = ((PogoInfo) symType).numInstrs;
                    return true;

                default:
                    if (symType.IsProc() && TryGetChild((BlockSym) symType, S_POGODATA, out var child))
                    {
                        staticSize = ((PogoInfo) child).numInstrs;
                        return true;
                    }

                    break;
            }

            staticSize = default;
            return false;
        }
    }
}
