﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_thunkOrdinal"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_thunkOrdinal"/>
        /// </summary>
        public static bool TryGetThunkOrdinal(in this SymType symType, out THUNK_ORDINAL thunkOrdinal)
        {
            switch (symType.rectyp)
            {
                //ThunkSym16
                case S_THUNK16:
                    thunkOrdinal = ((ThunkSym16) symType).ord;
                    return true;

                //ThunkSym32
                case S_THUNK32:
                case S_THUNK32_ST:
                    thunkOrdinal = ((ThunkSym32) symType).ord;
                    return true;
            }

            thunkOrdinal = default;
            return false;
        }
    }
}
