﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_type"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_type"/>
        /// </summary>
        public static bool TryGetType(in this SymType symType, out TypOrEnumType type)
        {
            switch (symType.rectyp)
            {
                //FrameRelSym
                case S_ATTR_FRAMEREL:
                case S_MANFRAMEREL:
                case S_MANFRAMEREL_ST:
                    type = ((FrameRelSym) symType).typind;
                    return true;

                //AttrManyRegSym2
                case S_ATTR_MANYREG:
                    type = ((AttrManyRegSym2) symType).typind;
                    return true;

                //AttrRegSym
                case S_ATTR_REGISTER:
                case S_MANREGISTER:
                case S_MANREGISTER_ST:
                    type = ((AttrRegSym) symType).typind;
                    return true;

                //AttrRegRel
                case S_ATTR_REGREL:
                case S_MANREGREL:
                case S_MANREGREL_ST:
                    type = ((AttrRegRel) symType).typind;
                    return true;

                //BPRelSym16
                case S_BPREL16:
                    type = ((BPRelSym16) symType).typind;
                    return true;

                //BPRelSym32
                case S_BPREL32:
                case S_BPREL32_ST:
                    type = ((BPRelSym32) symType).typind;
                    return true;

                //BPRelSym3216t
                case S_BPREL32_16t:
                    type = ((BPRelSym3216t) symType).typind;
                    return true;

                //CallSiteInfo
                case S_CALLSITEINFO:
                    type = ((CallSiteInfo) symType).typind;
                    return true;

                //UdtSym
                case S_COBOLUDT:
                case S_COBOLUDT_ST:
                case S_UDT:
                case S_UDT_ST:
                    type = ((UdtSym) symType).typind;
                    return true;

                //UdtSym16t
                case S_COBOLUDT_16t:
                case S_UDT_16t:
                    type = ((UdtSym16t) symType).typind;
                    return true;

                //ConstSym
                case S_CONSTANT:
                case S_CONSTANT_ST:
                case S_MANCONSTANT:
                    type = ((ConstSym) symType).typind;
                    return true;

                //ConstSym16t
                case S_CONSTANT_16t:
                    type = ((ConstSym16t) symType).typind;
                    return true;

                //FileStaticSym
                case S_FILESTATIC:
                    type = ((FileStaticSym) symType).typind;
                    return true;

                //DataSymHLSL
                case S_GDATA_HLSL:
                case S_LDATA_HLSL:
                    type = ((DataSymHLSL) symType).typind;
                    return true;

                //DataSymHLSL32
                case S_GDATA_HLSL32:
                case S_LDATA_HLSL32:
                    type = ((DataSymHLSL32) symType).typind;
                    return true;

                //DataSymHLSL32Ex
                case S_GDATA_HLSL32_EX:
                case S_LDATA_HLSL32_EX:
                    type = ((DataSymHLSL32Ex) symType).typind;
                    return true;

                //DataSym16
                case S_GDATA16:
                case S_LDATA16:
                case S_PUB16:
                    type = ((DataSym16) symType).typind;
                    return true;

                //DataSym32
                case S_GDATA32:
                case S_GDATA32_ST:
                case S_GMANDATA:
                case S_GMANDATA_ST:
                case S_GTHREAD32:
                case S_GTHREAD32_ST:
                case S_LDATA32:
                case S_LDATA32_ST:
                case S_LMANDATA:
                case S_LMANDATA_ST:
                case S_LTHREAD32:
                case S_LTHREAD32_ST:
                    type = ((DataSym32) symType).typind;
                    return true;

                //DataSym3216t
                case S_GDATA32_16t:
                case S_GTHREAD32_16t:
                case S_LDATA32_16t:
                case S_LTHREAD32_16t:
                case S_PUB32_16t:
                    type = ((DataSym3216t) symType).typind;
                    return true;

                //ProcSym16
                case S_GPROC16:
                case S_LPROC16:
                    type = ((ProcSym16) symType).typind;
                    return true;

                //ProcSym32
                case S_GPROC32:
                case S_GPROC32_ID:
                case S_GPROC32_ST:
                case S_LPROC32:
                case S_LPROC32_DPC:
                case S_LPROC32_DPC_ID:
                case S_LPROC32_ID:
                case S_LPROC32_ST:
                    type = ((ProcSym32) symType).typind;
                    return true;

                //ProcSym3216t
                case S_GPROC32_16t:
                case S_LPROC32_16t:
                    type = ((ProcSym3216t) symType).typind;
                    return true;

                //ProcSymIA64
                case S_GPROCIA64:
                case S_GPROCIA64_ID:
                case S_GPROCIA64_ST:
                case S_LPROCIA64:
                case S_LPROCIA64_ID:
                case S_LPROCIA64_ST:
                    type = ((ProcSymIA64) symType).typind;
                    return true;

                //ProcSymMips
                case S_GPROCMIPS:
                case S_GPROCMIPS_ID:
                case S_GPROCMIPS_ST:
                case S_LPROCMIPS:
                case S_LPROCMIPS_ID:
                case S_LPROCMIPS_ST:
                    type = ((ProcSymMips) symType).typind;
                    return true;

                //ProcSymMips16t
                case S_GPROCMIPS_16t:
                case S_LPROCMIPS_16t:
                    type = ((ProcSymMips16t) symType).typind;
                    return true;

                //HeapAllocSite
                case S_HEAPALLOCSITE:
                    type = ((HeapAllocSite) symType).typind;
                    return true;

                //LocalSym
                case S_LOCAL:
                    type = ((LocalSym) symType).typind;
                    return true;

                //LocalDPCGroupSharedSym
                case S_LOCAL_DPC_GROUPSHARED:
                    type = ((LocalDPCGroupSharedSym) symType).typind;
                    return true;

                //SlotSym32
                case S_LOCALSLOT:
                case S_LOCALSLOT_ST:
                case S_PARAMSLOT:
                case S_PARAMSLOT_ST:
                    type = ((SlotSym32) symType).typind;
                    return true;

                //AttrSlotSym
                case S_MANSLOT:
                case S_MANSLOT_ST:
                    type = ((AttrSlotSym) symType).typind;
                    return true;

                //ManTypRef
                case S_MANTYPREF:
                    type = ((ManTypRef) symType).typind;
                    return true;

                //ManyRegSym
                case S_MANYREG:
                case S_MANYREG_ST:
                    type = ((ManyRegSym) symType).typind;
                    return true;

                //ManyRegSym16t
                case S_MANYREG_16t:
                    type = ((ManyRegSym16t) symType).typind;
                    return true;

                //ManyRegSym2
                case S_MANYREG2:
                case S_MANYREG2_ST:
                    type = ((ManyRegSym2) symType).typind;
                    return true;

                //OemSymbol
                case S_OEM:
                    type = ((OemSymbol) symType).typind;
                    return true;

                //RefMiniPdb
                case S_REF_MINIPDB:
                    type = ((RefMiniPdb) symType).typind;
                    return true;

                //RegSym
                case S_REGISTER:
                case S_REGISTER_ST:
                    type = ((RegSym) symType).typind;
                    return true;

                //RegSym16t
                case S_REGISTER_16t:
                    type = ((RegSym16t) symType).typind;
                    return true;

                //RegRel16
                case S_REGREL16:
                    type = ((RegRel16) symType).typind;
                    return true;

                //RegRel32
                case S_REGREL32:
                case S_REGREL32_ST:
                    type = ((RegRel32) symType).typind;
                    return true;

                //RegRel3216t
                case S_REGREL32_16t:
                    type = ((RegRel3216t) symType).typind;
                    return true;
            }

            type = default;
            return false;
        }
    }
}
