﻿/*************************************************************************
 * This code was generated by a tool.                                    *
 * Please do not modify this file directly - modify _config.json instead *
 *************************************************************************/
using ClrDebug;
using ClrDebug.DIA;
using ClrDebug.PDB;
using static ClrDebug.PDB.SYM_ENUM_e;

namespace PESpy.PDB
{
    public static partial class SymTypeExtensions
    {
        /// <summary>
        /// <inheritdoc cref="IDiaSymbol.get_uavSlot"/><para/>
        /// Corresponds to <see cref="IDiaSymbol.get_uavSlot"/>
        /// </summary>
        public static bool TryGetUavSlot(in this SymType symType, out int uavSlot)
        {
            switch (symType.rectyp)
            {
                //DataSymHLSL32
                case S_GDATA_HLSL32:
                case S_LDATA_HLSL32:
                    uavSlot = ((DataSymHLSL32) symType).uavslot;
                    return true;
            }

            uavSlot = default;
            return false;
        }
    }
}
