/***********************************************************************
 * This code was generated by a tool.                                  *
 * Please do not modify this file directly - modify Locator.tt instead *
 ***********************************************************************/
using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using static PESpy.IMAGE_DEBUG_TYPE;

namespace PESpy
{
    /* Locator that attempts to implement the same logic as microsoft-pdb/DIA
     *
     * There are three kinds of symbols that can be used with PE files
     * - COFF
     * - CodeView (OMF)
     * - PDB
     *
     * Microsoft refers to OMF-style CodeView symbols as simply "CodeView", however that is very confusing to modern developers who typically consider
     * IMAGE_DEBUG_TYPE_CODEVIEW to be synonymous with PDBs. As such, we will refer to these types of symbols as OMF
     *
     * All three of these symbol types may exist in the PE File's debug table, or may have been split out into a separate *.dbg file.
     *
     * The principal purpose of microsoft-pdb's locator is to locate PDBs. There are three steps involved in locating a PDB
     *
     * 1. CrackExeOrDbg - analyze the headers of an *.exe or *.dbg file to find an IMAGE_DEBUG_TYPE_CODEVIEW record that points to a *.pdb file, or in the case of an *.exe file only,
     *                    find an IMAGE_DEBUG_TYPE_MISC that points to a *.dbg file (that we're hoping may in turn point to a *.pdb file)
     *
     *                    Modern versions of LOCATOR also include support for IMAGE_DEBUG_TYPE_EMBEDDED_PORTABLE_PDB
     *
     * 2. LocateDbg     - attempt to find the *.dbg file that was pointed to by the *.exe file. If the original input file was a *.dbg file, or the *.exe file did not
     *                    point to a *.dbg file, there's nothing to do here
     * 3. LocatePdb     - attempt to find the *.pdb file that was pointed to by either the *.exe file (from Step 1) or the *.dbg file (from either Step 1 or Step 2)
     *
     * Note that while LOCATOR may support passing in either an *.exe or *.dbg file, IDiaDataSource::loadDataForExe does not, because it's going to try
     * and validate the found PDB against the headers of the input file, which is not an exe
     *
     * The rules for locating *.dbg files are as follows
     *
     * 1. Is the target in the same folder as its parent (directory of parent + filename of parent + ".dbg"). Observe that the misc path is ignored, and that unlike PDBs
     *    DBG files do not ever have full paths listed, so we don't check the full original path
     * 3a. Is the target in any sub-string of the user supplied search path, %_NT_ALT_SYMBOL_PATH%, %_NT_SYMBOL_PATH% or %SystemRoot% at
     *
     *     If misc path is present:
     *
     *         C:\foo\symbols\<miscPath>
     *         C:\foo\<miscPath>
     *
     *         i.e. if misc path is exe\Test.dbg, this will try
     *
     *             C:\foo\symbols\exe\Test.dbg
     *             C:\foo\exe\Test.dbg
     *
     *         Note that we don't try and be "smart" and look at C:\foo\symbols\Text.dbg. We look directly at the misc path we're given. Special logic
     *         for handling the original EXE file extension does not apply
     *
     *     if misc path is not present:
     *
     *         C:\foo\symbols\<peFileExt>\<exeFileName>.dbg
     *         C:\foo\<peFileExt>\<exeFileName>.dbg
     *         C:\foo\exeFileName>.dbg
     *
     * The rules for locating *.pdb files are as follows
     *
     * 1. Is the target in the same folder as its parent (directory of parent + filename + extension listed in the IMAGE_DEBUG_TYPE_CODEVIEW record)
     * 2. Is the target at the literal path pointed to by the IMAGE_DEBUG_TYPE_CODEVIEW record? Sometimes this is an absolute path, sometimes relative
     * 3s. Is the target in any sub-string of the user supplied search path, %_NT_ALT_SYMBOL_PATH%, %_NT_SYMBOL_PATH% or %SystemRoot% at
     *     C:\foo\symbols\<ext>\<pdbFileName> (where <ext> is the file extension of the PE File if one was specified)
     *     C:\foo\<ext>\\<pdbFileName
     *     C:\foo\<pdbFileName>
     *
     *     where <pdbFileName> is the file name and extension listed in the IMAGE_DEBUG_TYPE_CODEVIEW record
     *
     * 3b. Or, if a sub-string of a user supplied search path begins with srv*, symsrv* or cache*:
     *
     *     Does the name + extension specified in the IMAGE_DEBUG_TYPE_CODEVIEW record exist on the symbol server? Any leading directory in the path should be stripped
     *
     * _NT_ALT_SYMBOL_PATH _is_ meant to come before _NT_SYMBOL_PATH; the purpose of it is to override the normal symbol path to point to private symbols that aren't available
     * in the normal _NT_SYMBOL_PATH. (Also note that while there is a method LOCATOR::FLocateDbgServer, this method is now empty. All of the symsrv handling logic is carried out in steps 2-5)
     */

    //Describes the situations in which Locator can execute HTTP requests for locating missing files
    public enum LocatorHttpPolicy
    {
        /// <summary>
        /// Locator may not execute HTTP requests for resolving missing symbols. Any files that have already
        /// been downloaded to the symbol store may be used
        /// </summary>
        None,

        /// <summary>
        /// Locator may only execute HTTP requests for files that are listed as being produced by Microsoft.
        /// This setting only works when the input file is a <see cref="PEFile"/>.
        /// </summary>
        Microsoft,

        /// <summary>
        /// Locator may execute HTTP requests for locating both Microsoft and Third Party symbols.
        /// </summary>
        All,
    }

    public interface ILocatorProgress
    {
        void Notify(LocatorProgressEventArgs eventArgs);
    }

    public static class Locator
    {
        private static string[] environmentNames =
        {
            "_NT_ALT_SYMBOL_PATH",
            "_NT_SYMBOL_PATH",
            "SystemRoot"
        };

        #region String -> Artifacts

        //Locate all artifacts associated with a given *.exe or *.dbg file

        /// <summary>
        /// Locates all debug artifacts associated with a given *.exe or *.dbg file.
        /// </summary>
        /// <param name="exeOrDbgPath">The path to the *.exe or *.dbg file to resolve debug artifacts for.</param>
        /// <param name="result">Stores all debug artifacts that were found.</param>
        /// <param name="symStoreKey">If a debug artifact was found on the symbol server, stores the <see cref="SymStoreKey"/> of the best artifact that was found on the symbol server.</param>
        /// <param name="httpPolicy">Specifies under what circumstance the <see cref="Locator"/> should be allowed to make HTTP requests to external symbol servers for locating debug artifacts.</param>
        /// <param name="searchPath">A custom search path that should be used for locating symbols. This value must match the standard format used by symbol paths.<para/>
        /// For more info, see MSDN: <see href="https://learn.microsoft.com/en-us/windows/win32/debug/symbol-paths"/></param>
        /// <param name="progress">An object that can be used to receive progress notifications as <see cref="Locator"/> tries to resolve symbols from upstream symbol stores.</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>True if any artifacts could be found. Otherwise, false.</returns>
        public static bool TryLocate(
            string exeOrDbgPath,
            out Artifacts result,
            out SymStoreKey? symStoreKey,
            LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All,
            string? searchPath = null,
            ILocatorProgress progress = null,
            CancellationToken cancellationToken = default)
        {
            Artifacts? artifacts;
            (artifacts, symStoreKey) = LocateInternal(exeOrDbgPath, null, SearchFlags.All, httpPolicy, searchPath, progress, cancellationToken);

            if (artifacts != null)
            {
                result = artifacts.Value;
                return true;
            }

            result = default;
            return false;
        }

#if !NATIVEAOT
        public static ValueTask<(Artifacts? artifacts, SymStoreKey? symStoreKey)> TryLocateAsync(string exeOrDbgPath, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, string? searchPath = null, ILocatorProgress progress = null, CancellationToken cancellationToken = default) =>
            LocateInternalAsync(exeOrDbgPath, null, SearchFlags.All, httpPolicy, searchPath, progress, cancellationToken);
#endif

        #endregion
        #region IFile -> Artifacts

        public static bool TryLocate(
            IFile exeOrDbgFile,
            out Artifacts result,
            out SymStoreKey? symStoreKey, //If the file was found on the symbol store, contains the key that was used to identify the file
            LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All,
            string? searchPath = null,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            if (exeOrDbgFile.FileName == null)
            {
                result = default;
                symStoreKey = default;
                return false;
            }

            Artifacts? artifacts;

            (artifacts, symStoreKey) = LocateInternal(null, exeOrDbgFile, SearchFlags.All, httpPolicy, searchPath, progress, cancellationToken);

            if (artifacts != null)
            {
                result = artifacts.Value;
                return true;
            }

            result = default;
            return false;
        }

#if !NATIVEAOT
        public static ValueTask<(Artifacts? artifacts, SymStoreKey? symStoreKey)> TryLocateAsync(IFile exeOrDbgFile, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, string? searchPath = null, ILocatorProgress progress = null, CancellationToken cancellationToken = default) =>
            LocateInternalAsync(null, exeOrDbgFile, SearchFlags.All, httpPolicy, searchPath, progress, cancellationToken);
#endif

        #endregion
        #region SymStoreKey -> String

        public static string Locate(SymStoreKey key, ILocatorProgress progress = null, CancellationToken cancellationToken = default)
        {
            if (!TryLocate(key, out var result, progress, cancellationToken))
                throw new FileNotFoundException($"Failed to locate the file associated with {nameof(SymStoreKey)} '{key}'");

            return result;
        }

        //Locate a file with a given key from the symbol server
        public static bool TryLocate(SymStoreKey key, out string? result, ILocatorProgress progress = null, CancellationToken cancellationToken = default)
        {
            result = TryLocateInternal(key, progress, default);

            return result != null;
        }

#if !NATIVEAOT
        public static ValueTask<string?> TryLocateAsync(
            SymStoreKey key,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default) => TryLocateInternalAsync(key, progress, cancellationToken);
#endif

        //We don't support LocatorHttpPolicy here because we don't need to load the file, and don't currently pass along
        //the path to the file to the HttpSymStore in order to load it
        private static string? TryLocateInternal(
            SymStoreKey key,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            var nameToLocate = Path.GetFileNameWithoutExtension(key.Index);
            var extToUse = Path.GetExtension(key.Index);

            foreach (var environmentName in environmentNames)
            {
                var environmentPath = Environment.GetEnvironmentVariable(environmentName);

                var result = LocateFileInPath(null, nameToLocate, environmentPath, extToUse, key, null, allowRemote: true, LocatorHttpPolicy.All, progress, cancellationToken);

                if (result.fileInPath != null)
                    return result.fileInPath;
            }

            return default;
        }

#if !NATIVEAOT
        //We don't support LocatorHttpPolicy here because we don't need to load the file, and don't currently pass along
        //the path to the file to the HttpSymStore in order to load it
        private static async ValueTask<string?> TryLocateInternalAsync(
            SymStoreKey key,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            var nameToLocate = Path.GetFileNameWithoutExtension(key.Index);
            var extToUse = Path.GetExtension(key.Index);

            foreach (var environmentName in environmentNames)
            {
                var environmentPath = Environment.GetEnvironmentVariable(environmentName);

                var result = await LocateFileInPathAsync(null, nameToLocate, environmentPath, extToUse, key, null, allowRemote: true, LocatorHttpPolicy.All, progress, cancellationToken).ConfigureAwait(false);

                if (result.fileInPath != null)
                    return result.fileInPath;
            }

            return default;
        }
#endif

        #endregion
        #region String -> String (DBG)

        //Locate the *.dbg file associated with a given *.exe, or returns the *.dbg file itself
        public static bool TryLocateDBG(
            string exeOrDbgPath,
            out string? result,
            LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All,
            string? searchPath = null,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            var (artifacts, _) = LocateInternal(exeOrDbgPath, null, SearchFlags.DBG, httpPolicy, searchPath, progress, cancellationToken);

            result = artifacts?.DBGPath;

            return result != null;
        }

#if !NATIVEAOT
        public static async ValueTask<string?> TryLocateDBGAsync(
            string exeOrDbgPath,
            LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All,
            string? searchPath = null,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            var (artifacts, _) = await LocateInternalAsync(exeOrDbgPath, null, SearchFlags.DBG, httpPolicy, searchPath, progress, cancellationToken).ConfigureAwait(false);

            var result = artifacts?.DBGPath;

            return result;
        }
#endif

        #endregion
        #region String -> String (PDB)

        //Locate the *.pdb associated with a given *.exe or *.dbg file

        public static string LocatePDB(SymStoreKey exeOrDbgKey, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, ILocatorProgress? progress = null)
        {
            var exeOrDbgPath = Locate(exeOrDbgKey, progress);

            return LocatePDB(exeOrDbgPath, httpPolicy, progress: progress);
        }

        public static string LocatePDB(string exeOrDbgPath, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, string? searchPath = null, ILocatorProgress? progress = null, CancellationToken cancellationToken = default)
        {
            if (!TryLocatePDB(exeOrDbgPath, out var result, httpPolicy, searchPath, progress, cancellationToken))
                throw new FileNotFoundException($"Failed to locate the PDB associated with file '{exeOrDbgPath}'");

            return result;
        }

        public static bool TryLocatePDB(string exeOrDbgPath, out string? result, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, string? searchPath = null, ILocatorProgress? progress = null, CancellationToken cancellationToken = default)
        {
            var (artifacts, _) = LocateInternal(exeOrDbgPath, null, SearchFlags.PDB, httpPolicy, searchPath, progress, cancellationToken);

            result = artifacts?.PDBPath;

            return result != null;
        }

#if !NATIVEAOT
        public static async ValueTask<string?> TryLocatePDBAsync(
            string exeOrDbgPath,
            LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All,
            string? searchPath = null,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            var (artifacts, _) = await LocateInternalAsync(exeOrDbgPath, null, SearchFlags.PDB, httpPolicy, searchPath, progress, cancellationToken).ConfigureAwait(false);

            if (artifacts != null)
                return artifacts.Value.PDBPath;

            return default;
        }
#endif

        #endregion
        #region String -> IFile (PDB)

        public static string LocatePDB(IFile exeOrDbgPath, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, string? searchPath = null, ILocatorProgress? progress = null, CancellationToken cancellationToken = default)
        {
            if (!TryLocatePDB(exeOrDbgPath, out var result, httpPolicy, searchPath, progress))
                throw new FileNotFoundException($"Failed to locate the PDB associated with file '{exeOrDbgPath}'");

            return result;
        }

        public static bool TryLocatePDB(IFile exeOrDbgFile, out string? result, LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All, string? searchPath = null, ILocatorProgress? progress = null)
        {
            result = TryLocatePDBFromFileInternal(exeOrDbgFile, httpPolicy, searchPath, progress);

            return result != null;
        }

#if !NATIVEAOT
        public static ValueTask<string?> TryLocatePDB(
            IFile exeOrDbgFile,
            LocatorHttpPolicy httpPolicy = LocatorHttpPolicy.All,
            string? searchPath = null,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default) =>
            TryLocatePDBFromFileInternalAsync(exeOrDbgFile, httpPolicy, searchPath, progress, cancellationToken);
#endif

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static string? TryLocatePDBFromFileInternal(
            IFile exeOrDbgFile,
            LocatorHttpPolicy httpPolicy,
            string? searchPath,
            ILocatorProgress? progress,
            CancellationToken cancellationToken = default)
        {
            if (exeOrDbgFile == null)
                throw new ArgumentNullException(nameof(exeOrDbgFile));

            var (artifacts, _) = LocateInternal(null, exeOrDbgFile, SearchFlags.PDB, httpPolicy, searchPath, progress, cancellationToken);

            if (artifacts != null)
                return artifacts.Value.PDBPath;

            return default;
        }

#if !NATIVEAOT
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static async ValueTask<string?> TryLocatePDBFromFileInternalAsync(
            IFile exeOrDbgFile,
            LocatorHttpPolicy httpPolicy,
            string? searchPath,
            ILocatorProgress? progress,
            CancellationToken cancellationToken = default)
        {
            if (exeOrDbgFile == null)
                throw new ArgumentNullException(nameof(exeOrDbgFile));

            var (artifacts, _) = await LocateInternalAsync(null, exeOrDbgFile, SearchFlags.PDB, httpPolicy, searchPath, progress, cancellationToken).ConfigureAwait(false);

            if (artifacts != null)
                return artifacts.Value.PDBPath;

            return default;
        }
#endif

        #endregion
        #region String -> EmbeddedPortablePdb

        //Locate the embedded portable PDB associated with a given *.exe or *.dbg file. Realistically,
        //it should not be possible to have an Embedded Portable PDB inside a *.dbg file (since *.dbg files predate MPDB's)
        public static bool TryLocateEmbeddedPortablePDB(
            string exeOrDbgPath,
            out int? debugDirectoryIndex,
            string? searchPath = null,
            ILocatorProgress? progress = null,
            CancellationToken cancellationToken = default)
        {
            var (artifacts, _) = LocateInternal(exeOrDbgPath, null, SearchFlags.MPDB, LocatorHttpPolicy.None, searchPath, progress, cancellationToken);

            if (artifacts != null)
            {
                debugDirectoryIndex = artifacts.Value.EmbeddedPortablePdbIndex;
                return debugDirectoryIndex != null;
            }

            debugDirectoryIndex = default;
            return false;
        }

        #endregion

        class LocatorContext
        {
            public ImageDebugDirectory[]? DebugTable;
            public SearchFlags Flags;
            public IFile File;
            public string? SearchPath;
            public string? PEFileExt;
            public bool Stripped;
            public bool NGEN;

            public uint PETimeDateStamp;
            public int PESizeOfImage;

            //If a file was ultimately located using a key, stores the key that was used in the locating
            public SymStoreKey? SymStoreKey;

            public string? DBGFilePath;
            public string? PDBFilePath;
            public string? SYMFilePath; //Strictly speaking you can generate *.map files for PE files too, but we only consider *.sym files for NE and LE files
            public int? MPDBIndex;
        }

        #region LocateInternal

        private static (Artifacts? artifacts, SymStoreKey? symStoreKey) LocateInternal(
            string? exeOrDbgPath,
            IFile? file,
            SearchFlags flags,
            LocatorHttpPolicy httpPolicy,
            string? searchPath,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            SetupLocate(ref exeOrDbgPath, file, flags, ref searchPath, out var ownsPEFile, out var state, out var ctx, out var run);

            try
            {
                while (run)
                {
                    switch (state)
                    {
                        case State.None:
                            if (!ReadFile(exeOrDbgPath, file, ref ctx, ref state, ref run))
                                return default;
                            break;

                        case State.ReadDebugTable:
                            if ((state = ReadDebugTable(ctx, httpPolicy, progress, cancellationToken)) == State.None)
                                run = false;
                            break;

                        case State.ReadMiscDebugTable: //An *.exe file pointed to a *.dbg file. Read the debug table of that *.dbg file
                            if (ParseMisc(ref ctx, ref ownsPEFile, ref run))
                                goto case State.ReadDebugTable;
                            break;

                        case State.ReadAnyLocal:
                            if (!ReadAnyLocal(exeOrDbgPath, searchPath, ref ctx))
                                return default;
                            run = false;
                            break;

                        case State.End:
                            run = false;
                            break;

                        default:
                            throw new NotImplementedException($"Don't know how to handle {nameof(State)} '{state}'");
                    }
                }

                return CreateArtifacts(ref ctx);
            }
            finally
            {
                if (ownsPEFile)
                    ctx.File?.Dispose();
            }
        }

#if !NATIVEAOT
        private static async ValueTask<(Artifacts? artifacts, SymStoreKey? symStoreKey)> LocateInternalAsync(
            string? exeOrDbgPath,
            IFile? file,
            SearchFlags flags,
            LocatorHttpPolicy httpPolicy,
            string? searchPath,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            SetupLocate(ref exeOrDbgPath, file, flags, ref searchPath, out var ownsPEFile, out var state, out var ctx, out var run);

            try
            {
                while (run)
                {
                    switch (state)
                    {
                        case State.None:
                            if (!ReadFile(exeOrDbgPath, file, ref ctx, ref state, ref run))
                                return default;
                            break;

                        case State.ReadDebugTable:
                            if ((state = await ReadDebugTableAsync(ctx, httpPolicy, progress, cancellationToken).ConfigureAwait(false)) == State.None)
                                run = false;
                            break;

                        case State.ReadMiscDebugTable: //An *.exe file pointed to a *.dbg file. Read the debug table of that *.dbg file
                            if (ParseMisc(ref ctx, ref ownsPEFile, ref run))
                                goto case State.ReadDebugTable;
                            break;

                        case State.ReadAnyLocal:
                            if (!ReadAnyLocal(exeOrDbgPath, searchPath, ref ctx))
                                return default;
                            run = false;
                            break;

                        case State.End:
                            run = false;
                            break;

                        default:
                            throw new NotImplementedException($"Don't know how to handle {nameof(State)} '{state}'");
                    }
                }

                return CreateArtifacts(ref ctx);
            }
            finally
            {
                if (ownsPEFile)
                    ctx.File?.Dispose();
            }
        }
#endif
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void SetupLocate(
            ref string? exeOrDbgPath,
            IFile? file,
            SearchFlags flags,
            ref string? searchPath,
            out bool ownsPEFile,
            out State state,
            out LocatorContext ctx,
            out bool run)
        {
            if (exeOrDbgPath == null && file == null)
                throw new ArgumentNullException(nameof(exeOrDbgPath));

            ownsPEFile = true;

            if (file != null)
            {
                ownsPEFile = false;
                exeOrDbgPath = file.FileName;

                if (exeOrDbgPath == null)
                    throw new ArgumentException("The specifid file does not have a FileName");
            }

            /* Systems often don't have _NT_SYMBOL_PATH defined, so it's up to us to define it for them. The way we'll do this is we'll say if it's not defined,
             * we'll append it to the user's custom search path and store any symbols we locate in %temp%
             *
             * Note that when RDP'd into a server, the temp path may include a session number at the end, and that folder
             * may not actually exist. When we go to save the file, we'll check if this directory exists, and if not create it */
            if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("_NT_SYMBOL_PATH")))
            {
                const string extraSearchPath = "srv*%temp%\\symbols*http://msdl.microsoft.com/download/symbols";

                if (searchPath == null)
                    searchPath = extraSearchPath;
                else
                {
                    using var builder = new ValueStringBuilder(searchPath.Length + extraSearchPath.Length + 1);
                    builder.Append(searchPath);
                    builder.Append(';');
                    builder.Append(extraSearchPath);

                    searchPath = builder.ToString();
                }
            }

            state = State.None;

            ctx = new LocatorContext
            {
                Flags = flags,
                SearchPath = searchPath,
            };

            run = true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadFile(
            string? exeOrDbgPath,
            IFile? file,
            ref LocatorContext ctx,
            ref State state,
            ref bool run)
        {
            if ((ctx.File = file!) != null || Detector.TryOpenFile(exeOrDbgPath, out ctx.File))
            {
                switch (ctx.File.Kind)
                {
                    case FileKind.PE:
                        var peFile = (PEFile) ctx.File;
                        ctx.DebugTable = peFile.DebugTable;
                        state = State.ReadDebugTable;

                        var dot = exeOrDbgPath.LastIndexOf('.');

                        if (dot == -1)
                            ctx.PEFileExt = string.Empty;
                        else
                            ctx.PEFileExt = exeOrDbgPath.Substring(dot + 1);

                        ctx.Stripped = (peFile.FileHeader.Characteristics & IMAGE_FILE.IMAGE_FILE_DEBUG_STRIPPED) != 0;
                        ctx.PETimeDateStamp = peFile.FileHeader.TimeDateStamp;
                        ctx.PESizeOfImage = peFile.OptionalHeader.SizeOfImage;

                        if (exeOrDbgPath!.EndsWith(".ni.exe") || exeOrDbgPath.EndsWith(".ni.dll"))
                        {
                            //Possible NGEN file
                            if (peFile.NgenHeader != null)
                                ctx.NGEN = true;
                        }

                        break;

                    case FileKind.DBG:
                        ctx.DBGFilePath = exeOrDbgPath;
                        ctx.DebugTable = ((DBGFile) ctx.File).DebugTable;
                        state = State.ReadDebugTable;

                        break;

                    case FileKind.DOS:
                    case FileKind.NE:
                    case FileKind.LE:
                        //Look for *.sym, *.dbg or *.pdb files in the same directory as us
                        state = State.ReadAnyLocal;

                        break;

                    default:
                        return false;
                }
            }
            else
                run = false;

            return true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static unsafe bool ReadAnyLocal(string exeOrDbgPath, string? searchPath, ref LocatorContext ctx)
        {
            var dot = exeOrDbgPath.LastIndexOf('.');

            if (dot == -1)
                return false;

            //Can't use "using" ebcause we set the length
            var builder = new ValueStringBuilder();

            try
            {
                var baseName = exeOrDbgPath.AsSpan(0, dot + 1);
                builder.Append(baseName);

                var pos = builder.Length;

                //Is there a .pdb file?
                builder.Append("pdb");
                var candidatePath = builder.ToString();

                if (File.Exists(candidatePath))
                {
                    ctx.PDBFilePath = candidatePath;
                    return true;
                }

                //Is there a .dbg file?
                builder.Length = pos;
                builder.Append("dbg");
                candidatePath = builder.ToString();

                if (File.Exists(candidatePath))
                {
                    ctx.DBGFilePath = candidatePath;
                    return true;
                }

                //Is there a .sym file?
                builder.Length = pos;
                builder.Append("sym");
                candidatePath = builder.ToString();

                if (File.Exists(candidatePath))
                {
                    ctx.SYMFilePath = candidatePath;
                    return true;
                }

                if (searchPath != null)
                {
                    //Try our search path as well. Note that we're not going to allow searching remote so we can just
                    //call the non-async version

                    builder.Clear();
                    var nameWithoutExt = Path.GetFileNameWithoutExtension(exeOrDbgPath);
                    builder.Append(nameWithoutExt);
                    builder.Append(".pdb");

                    var nameToLocate = builder.ToString();

                    string ext;

                    if (dot == -1)
                        ext = string.Empty;
                    else
                        ext = exeOrDbgPath.Substring(dot + 1);

                    fixed (char* p = nameToLocate)
                    {
                        var extSpan = new Span<char>(p + nameWithoutExt.Length + 1, 3);

                        var result = LocateFileInPath(null, nameToLocate, searchPath, ext, default, null, allowRemote: false, LocatorHttpPolicy.None, null, default);

                        if (result.fileInPath != null)
                        {
                            ctx.PDBFilePath = candidatePath;
                            return true;
                        }

                        "dbg".AsSpan().CopyTo(extSpan);

                        result = LocateFileInPath(null, nameToLocate, searchPath, ext, default, null, allowRemote: false, LocatorHttpPolicy.None, null, default);

                        if (result.fileInPath != null)
                        {
                            ctx.DBGFilePath = candidatePath;
                            return true;
                        }

                        "sym".AsSpan().CopyTo(extSpan);

                        result = LocateFileInPath(null, nameToLocate, searchPath, ext, default, null, allowRemote: false, LocatorHttpPolicy.None, null, default);

                        if (result.fileInPath != null)
                        {
                            ctx.SYMFilePath = candidatePath;
                            return true;
                        }
                    }
                }

                return false;
            }
            finally
            {
                builder.Dispose();
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ParseMisc(ref LocatorContext ctx, ref bool ownsPEFile, ref bool run)
        {
            Debug.Assert(ctx.DBGFilePath != null);

            if (Detector.TryOpenFile(ctx.DBGFilePath, out var dbgFile))
            {
                if (dbgFile is not DBGFile d)
                {
                    dbgFile.Dispose();
                    run = false;
                    return false;
                }

                if (!ownsPEFile)
                {
                    //We're replacing the file with the DBGFile, so we _will_ need to dispose that when we're done
                    ownsPEFile = false;
                }
                ctx.File = d;

                ctx.Stripped = false;
                ctx.DebugTable = d.DebugTable;

                //Now read the debug table like normal
                return true;
            }
            else
            {
                run = false;
                return false;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static (Artifacts? artifacts, SymStoreKey? symStoreKey) CreateArtifacts(ref LocatorContext ctx)
        {
            //Success is dictated by whether we found anything
            if (ctx.DBGFilePath == null && ctx.PDBFilePath == null && ctx.SYMFilePath == null && ctx.MPDBIndex == null)
                return default;

            ArtifactKind bestKind;

            if (ctx.PDBFilePath != null)
                bestKind = ArtifactKind.PDB;
            else if (ctx.MPDBIndex != null)
                bestKind = ArtifactKind.EmbeddedPortablePdb;
            else if (ctx.DBGFilePath != null)
                bestKind = ArtifactKind.DBG;
            else
            {
                Debug.Assert(ctx.SYMFilePath != null);
                bestKind = ArtifactKind.SYM;
            }

            return (new Artifacts(bestKind, ctx.DBGFilePath, ctx.PDBFilePath, ctx.SYMFilePath, ctx.MPDBIndex), ctx.SymStoreKey);
        }

        #endregion
        #region ReadDebugTable

        private static State ReadDebugTable(LocatorContext ctx, LocatorHttpPolicy httpPolicy, ILocatorProgress progress, CancellationToken cancellationToken)
        {
            if (ctx.DebugTable == null)
                return default;

            for (int i = 0; i < ctx.DebugTable.Length; i++)
            {
                ImageDebugDirectory debugDir = ctx.DebugTable[i];

                switch (debugDir.Type)
                {
                    case IMAGE_DEBUG_TYPE_MISC:
                        //It's possible for a *.dbg file to have a misc entry pointing back to the *.exe file. We only process misc entries when we're stripped,
                        //meaning we're processing the original PE file
                        if (ctx.Stripped && (ctx.Flags & SearchFlags.DBG) != 0 && debugDir.Data is ImageDebugMisc m)
                        {
                            var str = m.Data.ToString();

                            var symSrvIndex = SymStoreKey.FromMisc(str, ctx.PETimeDateStamp, ctx.PESizeOfImage);

                            var path = LocateDBGFile(ctx.File, str, ctx.SearchPath, ctx.PEFileExt, symSrvIndex, httpPolicy, progress, cancellationToken);

                            //If we've already found a file in another record, don't blow it away because we didn't find one in this one
                            if (path.filePath != null)
                            {
                                ctx.DBGFilePath = path.filePath;
                                ctx.SymStoreKey = path.keyUsed;
                                return State.ReadMiscDebugTable;
                            }
                        }
                        break;

                    case IMAGE_DEBUG_TYPE_CODEVIEW:
                        if ((ctx.Flags & SearchFlags.PDB) != 0 && debugDir.Data is ICodeViewPDB c)
                        {
                            var pdbName = c.Path.ToString();

                            if (ctx.NGEN)
                            {
                                if (!pdbName.EndsWith(".ni.pdb"))
                                    continue;
                            }
                            else
                            {
                                if (pdbName.EndsWith(".ni.pdb"))
                                    continue;
                            }

                            /* Per LOCATOR::FLocatePdb, if the debug directory's minor version is PORTABLE_PDB_MINOR_VERSION (20557) then
                             * this indicates that the PDB may in fact be a portable PDB, which can be resolved on the symbol server by
                             * specifying an age of -1. LOCATOR::FLocatePdb tries for a normal PDB first, and if that fails tries for
                             * a portable one. Visual Studio does not use LOCATOR, and if it sees that PORTABLE_PDB_MINOR_VERSION is present,
                             * it may attempt to do a direct lookup with a negative age specified */
                            SymStoreKey symSrvIndex;
                            SymStoreKey? altSymSrvIndex = null;

                            if (c is RSDSI r)
                            {
                                var rsdsPath = r.Path.ToString();

                                symSrvIndex = SymStoreKey.FromRSDSI(rsdsPath, r.Guid, r.Age);

                                if (debugDir.IsPortablePDB)
                                    altSymSrvIndex = SymStoreKey.FromRSDSI(rsdsPath, r.Guid, -1);
                            }
                            else
                            {
                                //I would not expect anything using NB10 to be using portable PDBs
                                symSrvIndex = SymStoreKey.FromNB10((NB10I) c);
                            }

                            var path = LocatePDBFile(ctx.File, pdbName, ctx.SearchPath, ctx.PEFileExt, symSrvIndex, altSymSrvIndex, httpPolicy, progress, cancellationToken);

                            //If we've already found a file in another record, don't blow it away because we didn't find one in this one
                            if (path.fileInPath != null)
                            {
                                ctx.PDBFilePath = path.fileInPath;
                                ctx.SymStoreKey = path.keyUsed;
                                return State.End;
                            }
                        }
                        break;

                    case IMAGE_DEBUG_TYPE_EMBEDDED_PORTABLE_PDB:
                        if ((ctx.Flags & SearchFlags.MPDB) != 0 && debugDir.Data is EmbeddedPortablePdb)
                        {
                            ctx.MPDBIndex = i;
                            return State.End;
                        }
                        break;
                }
            }

            return default;
        }

#if !NATIVEAOT
        private static async ValueTask<State> ReadDebugTableAsync(LocatorContext ctx, LocatorHttpPolicy httpPolicy, ILocatorProgress progress, CancellationToken cancellationToken)
        {
            if (ctx.DebugTable == null)
                return default;

            for (int i = 0; i < ctx.DebugTable.Length; i++)
            {
                ImageDebugDirectory debugDir = ctx.DebugTable[i];

                switch (debugDir.Type)
                {
                    case IMAGE_DEBUG_TYPE_MISC:
                        //It's possible for a *.dbg file to have a misc entry pointing back to the *.exe file. We only process misc entries when we're stripped,
                        //meaning we're processing the original PE file
                        if (ctx.Stripped && (ctx.Flags & SearchFlags.DBG) != 0 && debugDir.Data is ImageDebugMisc m)
                        {
                            var str = m.Data.ToString();

                            var symSrvIndex = SymStoreKey.FromMisc(str, ctx.PETimeDateStamp, ctx.PESizeOfImage);

                            var path = await LocateDBGFileAsync(ctx.File, str, ctx.SearchPath, ctx.PEFileExt, symSrvIndex, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

                            //If we've already found a file in another record, don't blow it away because we didn't find one in this one
                            if (path.filePath != null)
                            {
                                ctx.DBGFilePath = path.filePath;
                                ctx.SymStoreKey = path.keyUsed;
                                return State.ReadMiscDebugTable;
                            }
                        }
                        break;

                    case IMAGE_DEBUG_TYPE_CODEVIEW:
                        if ((ctx.Flags & SearchFlags.PDB) != 0 && debugDir.Data is ICodeViewPDB c)
                        {
                            var pdbName = c.Path.ToString();

                            if (ctx.NGEN)
                            {
                                if (!pdbName.EndsWith(".ni.pdb"))
                                    continue;
                            }
                            else
                            {
                                if (pdbName.EndsWith(".ni.pdb"))
                                    continue;
                            }

                            /* Per LOCATOR::FLocatePdb, if the debug directory's minor version is PORTABLE_PDB_MINOR_VERSION (20557) then
                             * this indicates that the PDB may in fact be a portable PDB, which can be resolved on the symbol server by
                             * specifying an age of -1. LOCATOR::FLocatePdb tries for a normal PDB first, and if that fails tries for
                             * a portable one. Visual Studio does not use LOCATOR, and if it sees that PORTABLE_PDB_MINOR_VERSION is present,
                             * it may attempt to do a direct lookup with a negative age specified */
                            SymStoreKey symSrvIndex;
                            SymStoreKey? altSymSrvIndex = null;

                            if (c is RSDSI r)
                            {
                                var rsdsPath = r.Path.ToString();

                                symSrvIndex = SymStoreKey.FromRSDSI(rsdsPath, r.Guid, r.Age);

                                if (debugDir.IsPortablePDB)
                                    altSymSrvIndex = SymStoreKey.FromRSDSI(rsdsPath, r.Guid, -1);
                            }
                            else
                            {
                                //I would not expect anything using NB10 to be using portable PDBs
                                symSrvIndex = SymStoreKey.FromNB10((NB10I) c);
                            }

                            var path = await LocatePDBFileAsync(ctx.File, pdbName, ctx.SearchPath, ctx.PEFileExt, symSrvIndex, altSymSrvIndex, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

                            //If we've already found a file in another record, don't blow it away because we didn't find one in this one
                            if (path.fileInPath != null)
                            {
                                ctx.PDBFilePath = path.fileInPath;
                                ctx.SymStoreKey = path.keyUsed;
                                return State.End;
                            }
                        }
                        break;

                    case IMAGE_DEBUG_TYPE_EMBEDDED_PORTABLE_PDB:
                        if ((ctx.Flags & SearchFlags.MPDB) != 0 && debugDir.Data is EmbeddedPortablePdb)
                        {
                            ctx.MPDBIndex = i;
                            return State.End;
                        }
                        break;
                }
            }

            return default;
        }
#endif

        #endregion
        #region LocateDBGFile

        //This method is only called when we have an IMAGE_DEBUG_MISC entry, and a *.dbg file should not have an IMAGE_DEBUG_MISC pointing to another file
        private static (string? filePath, SymStoreKey? keyUsed) LocateDBGFile(
            IFile file,
            string rawDbgName,
            string? searchPath,
            string? peFileExt,
            SymStoreKey symSrvIndex,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            var parentFullName = file.FileName!;

            //First, check for a file with the PE file name + ".dbg" in the same directory as the parent *.exe file
            var peBaseName = Path.GetFileNameWithoutExtension(parentFullName);

            var parentDir = Path.GetDirectoryName(parentFullName);

            var syntheticDbgName = peBaseName + ".dbg";

            var candidateDbgPath = Path.Combine(parentDir, syntheticDbgName);

            if (File.Exists(candidateDbgPath))
                return (candidateDbgPath, null);

            //We don't try string specified in the IMAGE_DEBUG_MISC directly; unlike with PDBs, it's never the full path to the *.dbg file

            string nameToLocate;
            string? extToUse = null;

            if (!string.IsNullOrEmpty(rawDbgName))
            {
                //We have a misc path. Try it as is
                nameToLocate = rawDbgName;
            }
            else
            {
                //We don't have a misc path. Synthesize a name from the PE file name
                nameToLocate = syntheticDbgName;
                extToUse = peFileExt; //We allow searching under an extension directory in this case
            }

            /* Now try search paths. There are four paths we try:
             * - the user supplied search path
             * - %_NT_ALT_SYMBOL_PATH%
             * - %_NT_SYMBOL_PATH%
             * - %SystemRoot%
             *
             * A search path is a sequence of semicolon delimited values describing locations that we should search
             * for the file. %SystemRoot% will just be C:\Windows, but the other 3 could be complex expressions like
             *
             * D:\MySymbols;srv*c:\symbols*http://msdl.microsoft.com/download/symbols
             */

            var result = LocateFileInPath(file, nameToLocate, searchPath, extToUse, symSrvIndex, null, allowRemote: true, httpPolicy, progress, cancellationToken);

            if (result.fileInPath != null)
                return result;

            foreach (var environmentName in environmentNames)
            {
                var environmentPath = Environment.GetEnvironmentVariable(environmentName);

                result = LocateFileInPath(file, nameToLocate, environmentPath, extToUse, symSrvIndex, null, allowRemote: true, httpPolicy, progress, cancellationToken);

                if (result.fileInPath != null)
                    return result;
            }

            //File was not found in any search path
            return default;
        }

#if !NATIVEAOT
        //This method is only called when we have an IMAGE_DEBUG_MISC entry, and a *.dbg file should not have an IMAGE_DEBUG_MISC pointing to another file
        private static async ValueTask<(string? filePath, SymStoreKey? keyUsed)> LocateDBGFileAsync(
            IFile file,
            string rawDbgName,
            string? searchPath,
            string? peFileExt,
            SymStoreKey symSrvIndex,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            var parentFullName = file.FileName!;

            //First, check for a file with the PE file name + ".dbg" in the same directory as the parent *.exe file
            var peBaseName = Path.GetFileNameWithoutExtension(parentFullName);

            var parentDir = Path.GetDirectoryName(parentFullName);

            var syntheticDbgName = peBaseName + ".dbg";

            var candidateDbgPath = Path.Combine(parentDir, syntheticDbgName);

            if (File.Exists(candidateDbgPath))
                return (candidateDbgPath, null);

            //We don't try string specified in the IMAGE_DEBUG_MISC directly; unlike with PDBs, it's never the full path to the *.dbg file

            string nameToLocate;
            string? extToUse = null;

            if (!string.IsNullOrEmpty(rawDbgName))
            {
                //We have a misc path. Try it as is
                nameToLocate = rawDbgName;
            }
            else
            {
                //We don't have a misc path. Synthesize a name from the PE file name
                nameToLocate = syntheticDbgName;
                extToUse = peFileExt; //We allow searching under an extension directory in this case
            }

            /* Now try search paths. There are four paths we try:
             * - the user supplied search path
             * - %_NT_ALT_SYMBOL_PATH%
             * - %_NT_SYMBOL_PATH%
             * - %SystemRoot%
             *
             * A search path is a sequence of semicolon delimited values describing locations that we should search
             * for the file. %SystemRoot% will just be C:\Windows, but the other 3 could be complex expressions like
             *
             * D:\MySymbols;srv*c:\symbols*http://msdl.microsoft.com/download/symbols
             */

            var result = await LocateFileInPathAsync(file, nameToLocate, searchPath, extToUse, symSrvIndex, null, allowRemote: true, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

            if (result.fileInPath != null)
                return result;

            foreach (var environmentName in environmentNames)
            {
                var environmentPath = Environment.GetEnvironmentVariable(environmentName);

                result = await LocateFileInPathAsync(file, nameToLocate, environmentPath, extToUse, symSrvIndex, null, allowRemote: true, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

                if (result.fileInPath != null)
                    return result;
            }

            //File was not found in any search path
            return default;
        }
#endif

        #endregion
        #region LocatePDBFile

        /// <summary>
        /// Top-level method for locating the path to a PDB file
        /// </summary>
        /// <param name="file">The parent *.exe or *.dbg file that contained an IMAGE_DEBUG_TYPE_CODEVIEW record pointing to a PDB.</param>
        /// <param name="rawPdbName">The raw PDB name listed in the IMAGE_DEBUG_TYPE_CODEVIEW record. This may simply be a file name + extension or an absolute path to a file.</param>
        /// <param name="searchPath">A semicolon delimited list of search paths to search for the PDB in.</param>
        /// <param name="peFileExt">If the original file we were asked to locate was a PE file, the file extension of that file.</param>
        /// <param name="symSrvIndex">The index of the PDB file on the symbol server.</param>
        /// <param name="altSymSrvIndex">The index of an alternate PDB file to locate on the symbol server if <paramref name="symSrvIndex"/> can't be found</param>
        /// <param name="httpPolicy">To what extent HTTP requests to external symbol servers should be allowed to resolve the PDB</param>
        /// <param name="progress">A callback that can receive notice of progress while copying files between stores.</param>
        /// <param name="cancellationToken">A token that can be used to receive notice of cancellation.</param>
        /// <returns>The path to the PDB file on the search path, or <see langword="null"/> if a PDB was not found.</returns>
        private static (string? fileInPath, SymStoreKey? keyUsed) LocatePDBFile(
            IFile file,
            string rawPdbName,
            string? searchPath,
            string? peFileExt,
            SymStoreKey symSrvIndex,
            SymStoreKey? altSymSrvIndex,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            var parentFullName = file.FileName!;

            //First, check for a file with the base name + extension of the file listed in the IMAGE_DEBUG_TYPE_CODEVIEW record
            //in the same directory as the parent *.exe or *.dbg file
            var pdbNameWithoutDir = Path.GetFileName(rawPdbName);

            var parentDir = Path.GetDirectoryName(parentFullName)!;

            var candidatePdbPath = Path.Combine(parentDir, pdbNameWithoutDir);

            if (File.Exists(candidatePdbPath))
                return (candidatePdbPath, null);

            //Next, try the original path listed in the IMAGE_DEBUG_TYPE_CODEVIEW record. Sometimes PDBs embed an absolute path
            if (File.Exists(rawPdbName))
                return (rawPdbName, null);

            /* Now try search paths. There are four paths we try:
             * - the user supplied search path
             * - %_NT_ALT_SYMBOL_PATH%
             * - %_NT_SYMBOL_PATH%
             * - %SystemRoot%
             *
             * A search path is a sequence of semicolon delimited values describing locations that we should search
             * for the file. %SystemRoot% will just be C:\Windows, but the other 3 could be complex expressions like
             *
             * D:\MySymbols;srv*c:\symbols*http://msdl.microsoft.com/download/symbols
             */

            var result = LocateFileInPath(file, pdbNameWithoutDir, searchPath, peFileExt, symSrvIndex, altSymSrvIndex, allowRemote: true, httpPolicy, progress, cancellationToken);

            if (result.fileInPath != null)
                return result;

            foreach (var environmentName in environmentNames)
            {
                var environmentPath = Environment.GetEnvironmentVariable(environmentName);

                result = LocateFileInPath(file, pdbNameWithoutDir, environmentPath, peFileExt, symSrvIndex, altSymSrvIndex, allowRemote: true, httpPolicy, progress, cancellationToken);

                if (result.fileInPath != null)
                    return result;
            }

            //File was not found in any search path
            return default;
        }

#if !NATIVEAOT
        /// <summary>
        /// Top-level method for locating the path to a PDB file
        /// </summary>
        /// <param name="file">The parent *.exe or *.dbg file that contained an IMAGE_DEBUG_TYPE_CODEVIEW record pointing to a PDB.</param>
        /// <param name="rawPdbName">The raw PDB name listed in the IMAGE_DEBUG_TYPE_CODEVIEW record. This may simply be a file name + extension or an absolute path to a file.</param>
        /// <param name="searchPath">A semicolon delimited list of search paths to search for the PDB in.</param>
        /// <param name="peFileExt">If the original file we were asked to locate was a PE file, the file extension of that file.</param>
        /// <param name="symSrvIndex">The index of the PDB file on the symbol server.</param>
        /// <param name="altSymSrvIndex">The index of an alternate PDB file to locate on the symbol server if <paramref name="symSrvIndex"/> can't be found</param>
        /// <param name="httpPolicy">To what extent HTTP requests to external symbol servers should be allowed to resolve the PDB</param>
        /// <param name="progress">A callback that can receive notice of progress while copying files between stores.</param>
        /// <param name="cancellationToken">A token that can be used to receive notice of cancellation.</param>
        /// <returns>The path to the PDB file on the search path, or <see langword="null"/> if a PDB was not found.</returns>
        private static async ValueTask<(string? fileInPath, SymStoreKey? keyUsed)> LocatePDBFileAsync(
            IFile file,
            string rawPdbName,
            string? searchPath,
            string? peFileExt,
            SymStoreKey symSrvIndex,
            SymStoreKey? altSymSrvIndex,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            var parentFullName = file.FileName!;

            //First, check for a file with the base name + extension of the file listed in the IMAGE_DEBUG_TYPE_CODEVIEW record
            //in the same directory as the parent *.exe or *.dbg file
            var pdbNameWithoutDir = Path.GetFileName(rawPdbName);

            var parentDir = Path.GetDirectoryName(parentFullName)!;

            var candidatePdbPath = Path.Combine(parentDir, pdbNameWithoutDir);

            if (File.Exists(candidatePdbPath))
                return (candidatePdbPath, null);

            //Next, try the original path listed in the IMAGE_DEBUG_TYPE_CODEVIEW record. Sometimes PDBs embed an absolute path
            if (File.Exists(rawPdbName))
                return (rawPdbName, null);

            /* Now try search paths. There are four paths we try:
             * - the user supplied search path
             * - %_NT_ALT_SYMBOL_PATH%
             * - %_NT_SYMBOL_PATH%
             * - %SystemRoot%
             *
             * A search path is a sequence of semicolon delimited values describing locations that we should search
             * for the file. %SystemRoot% will just be C:\Windows, but the other 3 could be complex expressions like
             *
             * D:\MySymbols;srv*c:\symbols*http://msdl.microsoft.com/download/symbols
             */

            var result = await LocateFileInPathAsync(file, pdbNameWithoutDir, searchPath, peFileExt, symSrvIndex, altSymSrvIndex, allowRemote: true, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

            if (result.fileInPath != null)
                return result;

            foreach (var environmentName in environmentNames)
            {
                var environmentPath = Environment.GetEnvironmentVariable(environmentName);

                result = await LocateFileInPathAsync(file, pdbNameWithoutDir, environmentPath, peFileExt, symSrvIndex, altSymSrvIndex, allowRemote: true, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

                if (result.fileInPath != null)
                    return result;
            }

            //File was not found in any search path
            return default;
        }
#endif

        #endregion
        #region LocateFileInPath

        private static (string? fileInPath, SymStoreKey? keyUsed) LocateFileInPath(
            IFile? file,
            string nameAndExt,
            string? searchPath,
            string? peFileExt,
            SymStoreKey symSrvIndex,
            SymStoreKey? altSymSrvIndex,
            bool allowRemote,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            if (searchPath == null)
                return default;

            var remainingSearchPath = new SpanInfo(searchPath);

            var builder = new ValueStringBuilder.NonRef(256);

            try
            {
                var run = true;

                while (run)
                {
                    //We can't store a ReadOnlySpan in the async version of the method, so we'll store the bounds here instead
                    SpanInfo currentPath = default; //I can't pass this to LocateFileInPathLocal for some reason if this is returned as an out parameter from LocateFileInPathSetup

                    if (!LocateFileInPathSetup(ref remainingSearchPath, ref currentPath, ref run, out var symSrv, out var cache))
                        return default;

                    if (symSrv || cache)
                    {
                        if (allowRemote)
                        {
                            var result = SymStore.GetFile(file, currentPath.Span, symSrvIndex, altSymSrvIndex, httpPolicy, progress, cancellationToken);

                            if (result.filePath != null)
                                return result;
                        }
                    }
                    else
                    {
                        if (LocateFileInPathLocal(ref builder, currentPath.Span, nameAndExt, peFileExt, out var str))
                            return (str, null);
                    }
                }

                return default;
            }
            finally
            {
                builder.Dispose();
            }
        }

#if !NATIVEAOT
        private static async ValueTask<(string? fileInPath, SymStoreKey? keyUsed)> LocateFileInPathAsync(
            IFile? file,
            string nameAndExt,
            string? searchPath,
            string? peFileExt,
            SymStoreKey symSrvIndex,
            SymStoreKey? altSymSrvIndex,
            bool allowRemote,
            LocatorHttpPolicy httpPolicy,
            ILocatorProgress progress,
            CancellationToken cancellationToken)
        {
            if (searchPath == null)
                return default;

            var remainingSearchPath = new SpanInfo(searchPath);

            var builder = new ValueStringBuilder.NonRef(256);

            try
            {
                var run = true;

                while (run)
                {
                    //We can't store a ReadOnlySpan in the async version of the method, so we'll store the bounds here instead
                    SpanInfo currentPath = default; //I can't pass this to LocateFileInPathLocal for some reason if this is returned as an out parameter from LocateFileInPathSetup

                    if (!LocateFileInPathSetup(ref remainingSearchPath, ref currentPath, ref run, out var symSrv, out var cache))
                        return default;

                    if (symSrv || cache)
                    {
                        if (allowRemote)
                        {
                            var result = await SymStore.GetFileAsync(file, currentPath.Span, symSrvIndex, altSymSrvIndex, httpPolicy, progress, cancellationToken).ConfigureAwait(false);

                            if (result.filePath != null)
                                return result;
                        }
                    }
                    else
                    {
                        if (LocateFileInPathLocal(ref builder, currentPath.Span, nameAndExt, peFileExt, out var str))
                            return (str, null);
                    }
                }

                return default;
            }
            finally
            {
                builder.Dispose();
            }
        }
#endif
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool LocateFileInPathSetup(ref SpanInfo remainingSearchPath, ref SpanInfo currentPath, ref bool run, out bool symSrv, out bool cache)
        {
            var index = remainingSearchPath.IndexOf(";".AsSpan(), StringComparison.OrdinalIgnoreCase);

            if (index == -1)
            {
                run = false;
                currentPath = remainingSearchPath; //Use the rest of the path

                remainingSearchPath = default;
            }
            else
            {
                currentPath = remainingSearchPath.Slice(0, index);

                //Update the current position for the next loop round
                remainingSearchPath = remainingSearchPath.Slice(index + 1);
            }

            symSrv = false;
            cache = false;

            if (currentPath.StartsWith("srv*".AsSpan(), StringComparison.OrdinalIgnoreCase))
            {
                symSrv = true;
                currentPath = currentPath.Slice(4);
            }
            else if (currentPath.StartsWith("symsrv*".AsSpan(), StringComparison.OrdinalIgnoreCase))
            {
                //Only symsrv.dll is supported
                if (!currentPath.StartsWith("symsrv*symsrv.dll*".AsSpan(), StringComparison.OrdinalIgnoreCase))
                    return false;

                symSrv = true;
                currentPath = currentPath.Slice(18);
            }

            return true;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool LocateFileInPathLocal(
            ref ValueStringBuilder.NonRef builder,
            ReadOnlySpan<char> currentPath,
            string nameAndExt,
            string? peFileExt,
            out string str)
        {
            builder.Clear();

            builder.Append(currentPath);

            if (!currentPath.EndsWith("\\".AsSpan()) && !currentPath.EndsWith("/".AsSpan()))
                builder.Append("\\");

            var prefix = builder.Length;

            const string symbolsPrefix = "symbols\\";

            builder.Append(symbolsPrefix);

            if (peFileExt != null)
            {
                builder.Append(peFileExt);
                builder.Append('\\');
            }

            builder.Append(nameAndExt);

            str = builder.ToString();

            if (File.Exists(str))
                return true;

            //Try without symbols\ prefix
            builder.Remove(prefix, symbolsPrefix.Length);

            str = builder.ToString();

            if (File.Exists(str))
                return true;

            if (peFileExt != null)
            {
                //If a PE File extension was specified, try without that now too
                builder.Remove(prefix, peFileExt.Length + 1);
                str = builder.ToString();

                if (File.Exists(str))
                    return true;
            }

            return false;
        }

        #endregion

        [Flags]
        enum SearchFlags
        {
            DBG = 1,
            PDB = 2,
            MPDB = 4,
            All = DBG | PDB | MPDB
        }

        public readonly struct Artifacts
        {
            public ArtifactKind BestKind { get; }

            public string? DBGPath { get; }

            public string? PDBPath { get; }

            //Only valid when the input file is a DOS, NE or LE file
            public string? SYMPath { get; }

            /// <summary>
            /// Gets the index of the <see cref="ImageDebugDirectory"/> that contains <see cref="EmbeddedPortablePdb"/> data.<para/>
            /// If this value is <see langword="null"/>, embedded portable PDB metadata is not available.
            /// </summary>
            public int? EmbeddedPortablePdbIndex { get; } //Note that this can't be the EmbeddedPortablePdb itself, because if only a path to a PEFile was passed in, we'll have opened and then closed the file

            public Artifacts(ArtifactKind bestKind, string? dbgPath, string? pdbPath, string? symPath, int? embeddedPortablePdbIndex)
            {
                BestKind = bestKind;
                DBGPath = dbgPath;
                PDBPath = pdbPath;
                SYMPath = symPath;
                EmbeddedPortablePdbIndex = embeddedPortablePdbIndex;
            }
        }

        public enum ArtifactKind
        {
            SYM = 1,
            DBG = 2,
            EmbeddedPortablePdb = 3,
            PDB = 4,
        }

        internal enum State
        {
            //The initial state. Read headers to find out what type of file it is
            None,

            //Read the debug table of the input *.exe or *.dbg file
            ReadDebugTable,

            //Read the debug table of a *.dbg file pointed to by an *.exe file
            ReadMiscDebugTable,

            //It's a DOS, NE or LE file; accept any *.sym, *.dbg or *.pdb file located in the same
            //directory as the input file
            ReadAnyLocal,

            End
        }

        internal struct SpanInfo
        {
            public string Value;
            public int StartIndex;
            public int Length;

            public SpanInfo(string value)
            {
                Value = value;
                Length = value.Length;
            }

            public ReadOnlySpan<char> Span => Value.AsSpan(StartIndex, Length);

            public override string ToString() => Span.ToString();

            public SpanInfo Slice(int startIndex) => new SpanInfo { Value = Value, StartIndex = StartIndex + startIndex, Length = Length - startIndex };

            public SpanInfo Slice(int startIndex, int length) => new SpanInfo { Value = Value, StartIndex = StartIndex + startIndex, Length = length };

            public int IndexOf(ReadOnlySpan<char> value, StringComparison comparisonType) => Span.IndexOf(value, comparisonType);

            public bool StartsWith(ReadOnlySpan<char> value, StringComparison comparisonType) => Span.StartsWith(value, comparisonType);
        }
    }
}
