<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(Build)ClrDebug.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\PESpy.xml</DocumentationFile>
		<DefineConstants Condition="'$(Configuration)' == 'Debug'">$(DefineConstants)</DefineConstants>
    <NoWarn>$(NoWarn);1591;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>$(NoWarn);1701;1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_old\**" />
    <None Include="_old\**" />

    <AdditionalFiles Include="BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PE\14. Cor20\Ecma335\Index\Index.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.tt</DependentUpon>
    </None>
    <None Include="Strings.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.5" PrivateAssets="all" />

    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="PE\14. Cor20\Ecma335\Index\Index.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Index.cs</LastGenOutput>
    </None>
    <None Update="Strings.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Strings.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PE\14. Cor20\Ecma335\Index\Index.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.tt</DependentUpon>
    </Compile>
    <Compile Update="Strings.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
