<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(Build)ClrDebug.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\PESpy.xml</DocumentationFile>
		<DefineConstants Condition="'$(Configuration)' == 'Debug'">$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_old\**" />
    <None Include="_old\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PE\14. Cor20\Ecma335\Index\Index.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="PE\14. Cor20\Ecma335\Index\Index.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Index.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PE\14. Cor20\Ecma335\Index\Index.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
