<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(Build)ClrDebug.props" />
  <Import Project="..\..\build\NuGet.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>annotations</Nullable>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\PESpy.xml</DocumentationFile>
		<DefineConstants Condition="'$(Configuration)' == 'Debug'">$(DefineConstants);MONITOR_NODE_CACHE</DefineConstants>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
		<AnalysisLevel>none</AnalysisLevel>
    <CheckForOverflowUnderflow Condition="'$(Configuration)' == 'Debug'">true</CheckForOverflowUnderflow>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Locator.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Locator.tt</DependentUpon>
    </None>
    <None Include="PE\14. Cor20\Ecma335\Index\Index.g.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.g.tt</DependentUpon>
    </None>
    <None Include="Strings.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.tt</DependentUpon>
    </None>
    <None Include="SymStore\FileSystemSymStore.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FileSystemSymStore.tt</DependentUpon>
    </None>
    <None Include="SymStore\SymStore.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SymStore.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.5" PrivateAssets="all" />

    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" PrivateAssets="all" />

    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Locator.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Locator.cs</LastGenOutput>
    </None>
    <None Update="PE\14. Cor20\Ecma335\Index\Index.g.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Index.g.cs</LastGenOutput>
    </None>
    <None Update="Strings.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Strings.cs</LastGenOutput>
    </None>
    <None Update="SymStore\FileSystemSymStore.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FileSystemSymStore.cs</LastGenOutput>
    </None>
    <None Update="SymStore\SymStore.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SymStore.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Locator.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Locator.tt</DependentUpon>
    </Compile>
    <Compile Update="PE\14. Cor20\Ecma335\Index\Index.g.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.g.tt</DependentUpon>
    </Compile>
    <Compile Update="Strings.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.tt</DependentUpon>
    </Compile>
    <Compile Update="SymStore\FileSystemSymStore.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FileSystemSymStore.tt</DependentUpon>
    </Compile>
    <Compile Update="SymStore\SymStore.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SymStore.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
