
/**********************************************************************************
 * This code was generated by a tool.                                             *
 * Please do not modify this file directly - modify ValueStringBuilder.cs instead *
 **********************************************************************************/
using System;
using System.Buffers;
#if !NET
using System.Buffers.Text;
#endif
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;

#nullable disable

namespace PESpy
{
    /// <summary>
    /// Represents a non-allocating string builder capable of being backed by a rented array.<para/>
    /// Unlike <see cref="ValueStringBuilder"/>, this type is not a ref-struct, and as such has slightly
    /// lower performance due to the JIT being unable to elide certain safety checks when converting the
    /// rented array to a span each time a method tries to use it. This type is designed for use in async
    /// methods (where ref-structs cannot be used) or when you need to store a string builder inside a class.
    /// </summary>
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    public partial struct PooledStringBuilder
    {
        internal static ReadOnlySpan<char> _escapeCharsUtf16 => new[]
        {
            '\n',
            '\r',
            '\0',
            '\t'
        };

        internal static ReadOnlySpan<byte> _escapeCharsUtf8 => new[]
        {
            (byte) '\n',
            (byte) '\r',
            (byte) '\0',
            (byte) '\t'
        };

        private string DebuggerDisplay => ToString().Replace("\0", "\\0");

        private char[] _chars;
        private int _pos;

        public PooledStringBuilder(int initialCapacity)
        {
            _chars = ArrayPool<char>.Shared.Rent(initialCapacity);
            _pos = 0;
        }

        public int Length
        {
            get => _pos;
            set
            {
                Debug.Assert(value >= 0);
                Debug.Assert(value <= _chars.Length);
                _pos = value;
            }
        }

        public int Capacity => _chars.Length;

        public void EnsureCapacity(int capacity)
        {
            // This is not expected to be called this with negative capacity
            Debug.Assert(capacity >= 0);

            // If the caller has a bug and calls this with negative capacity, make sure to call Grow to throw an exception.
            if ((uint) capacity > (uint) _chars.Length)
                Grow(capacity - _pos);
        }

        public ref char this[int index]
        {
            get
            {
                Debug.Assert(index < _pos);
                return ref _chars[index];
            }
        }

        public override string ToString()
        {
            string s = _chars.AsSpan(0, _pos).ToString();
            return s;
        }

        /// <summary>Returns the underlying storage of the builder.</summary>
        public Span<char> RawChars => _chars;

        /// <summary>
        /// Returns a span around the contents of the builder.
        /// </summary>
        /// <param name="terminate">Ensures that the builder has a null char after <see cref="Length"/></param>
        public ReadOnlySpan<char> AsSpan(bool terminate)
        {
            if (terminate)
            {
                EnsureCapacity(Length + 1);
                _chars[Length] = '\0';
            }
            return _chars.AsSpan(0, _pos);
        }

        public ReadOnlySpan<char> AsSpan() => _chars.AsSpan(0, _pos);
        public ReadOnlySpan<char> AsSpan(int start) => _chars.AsSpan(start, _pos - start);
        public ReadOnlySpan<char> AsSpan(int start, int length) => _chars.AsSpan(start, length);

        //Many APIs only work on ReadOnlySpan, so it makes sense to have that as the default
        //implementation of AsSpan(). But if we want to mess with the underylying buffer,
        //we now need a new way of doing that
        public Span<char> AsMutableSpan() => _chars.AsSpan(0, _pos);

        public bool TryCopyTo(Span<char> destination, out int charsWritten)
        {
            if (_chars.AsSpan(0, _pos).TryCopyTo(destination))
            {
                charsWritten = _pos;
                Dispose();
                return true;
            }
            else
            {
                charsWritten = 0;
                Dispose();
                return false;
            }
        }

        public void Insert(int index, char value, int count)
        {
            if (_pos > _chars.Length - count)
            {
                Grow(count);
            }

            int remaining = _pos - index;
            _chars.AsSpan(index, remaining).CopyTo(_chars.AsSpan(index + count));
            _chars.AsSpan(index, count).Fill(value);
            _pos += count;
        }

        public void Insert(int index, string s)
        {
            if (s == null)
            {
                return;
            }

            int count = s.Length;

            if (_pos > (_chars.Length - count))
            {
                Grow(count);
            }

            int remaining = _pos - index;
            _chars.AsSpan(index, remaining).CopyTo(_chars.AsSpan(index + count));
            s.AsSpan().CopyTo(_chars.AsSpan(index));
            _pos += count;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Append(char c)
        {
            int pos = _pos;
            Span<char> chars = _chars;
            if ((uint) pos < (uint) chars.Length)
            {
                chars[pos] = c;
                _pos = pos + 1;
            }
            else
            {
                GrowAndAppend(c);
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Append(long value)
        {
            var isNegative = value < 0;

            //Make the value signed
            var unsignedValue = isNegative
                ? (ulong) -value
                : (ulong) value;

            var numChars = 1 + (isNegative ? 1 : 0);

            var temp = value;

            while ((temp /= 10) != 0)
                numChars++;

            var pos = _pos;
            var dest = _chars;

            if (pos > dest.Length - numChars)
            {
                Grow(numChars);
                dest = _chars;
            }

            if (isNegative)
            {
                dest[pos++] = '-';
                numChars--;
            }

            var current = pos + numChars - 1;

            for (var i = 0; i < numChars; i++)
            {
                dest[current - i] = (char) ('0' + (unsignedValue % 10));
                unsignedValue /= 10;
            }

            pos += numChars;
            _pos = pos;
        }

        public unsafe void Append(float value)
        {
            //The real max is less than 40 but this'll do
            const int max = 40;
            EnsureCapacity(Length + max);

#if NET
            var result = value.TryFormat(_chars.AsSpan(Length), out var charsWritten);
            Debug.Assert(result);

            _pos += charsWritten;
#else
            byte* pBuffer = stackalloc byte[max];
            var buffer = new Span<byte>(pBuffer, max);

            var result = Utf8Formatter.TryFormat(value, buffer, out var bytesWritten);
            Debug.Assert(result);
            Append(buffer.Slice(0, bytesWritten));
#endif
        }

        public unsafe void Append(double value)
        {
            //The real max is less than 40, like float, but this'll do
            const int max = 80;
            EnsureCapacity(Length + max);

#if NET
            var result = value.TryFormat(_chars.AsSpan(Length), out var charsWritten);
            Debug.Assert(result);

            _pos += charsWritten;
#else
            byte* pBuffer = stackalloc byte[max];
            var buffer = new Span<byte>(pBuffer, max);

            var result = Utf8Formatter.TryFormat(value, buffer, out var bytesWritten);
            Debug.Assert(result);
            Append(buffer.Slice(0, bytesWritten));
#endif
        }

        public void Append(Guid value)
        {
#if NET
            EnsureCapacity(Length + 36);
            var result = value.TryFormat(_chars.AsSpan(Length), out var charsWritten);
            Debug.Assert(result);
            Debug.Assert(charsWritten == 36);

            _pos += 36;
#else
            Append(value.ToString());
#endif
        }

        public void Remove(int startIndex, int length)
        {
            if (length > Length - startIndex)
                throw new ArgumentOutOfRangeException();

            if (Length == length && startIndex == 0)
            {
                Length = 0;
                return;
            }

            if (Length > 0)
            {
                if (_chars != null)
                    Array.Copy(_chars, startIndex + length, _chars, startIndex, (Length - (startIndex + length)));
                else
                    _chars.AsSpan(startIndex + length, (Length - startIndex + length)).CopyTo(_chars.AsSpan(startIndex));

                Length -= length;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Append(string s)
        {
            if (s == null)
                return;

            int pos = _pos;
            if (s.Length == 1 && (uint) pos < (uint) _chars.Length) // very common case, e.g. appending strings from NumberFormatInfo like separators, percent symbols, etc.
            {
                _chars[pos] = s[0];
                _pos = pos + 1;
            }
            else
            {
                AppendSlow(s);
            }
        }

        private static string[] units =
        {
            "B",
            "KB",
            "MB",
            "GB",
            "TB"
        };

        public unsafe void AppendSize(double size, bool forceDecimal = false)
        {
            if (size < 0)
                throw new ArgumentException("Size cannot be negative");

            if (size < 1024)
            {
                Append((long) size);
                Append(" B");
                return;
            }

            var i = 0;

            while (size >= 1024 && i < units.Length - 1)
            {
                size /= 1024;
                i++;
            }

            //The real max is less than 40, like float, but this'll do
            const int max = 80;

            //F2 means always have 2 decimal places (1 -> 1.00)
            //N2 means include thousands separator
            //0.## will trim trailing 0's

#if NET
            EnsureCapacity(Length + max);
            var result = size.TryFormat(_chars.AsSpan(Length), out var charsWritten, forceDecimal ? "N2" : "0.##");
            Debug.Assert(result);

            _pos += charsWritten;
#else


            byte* pBuffer = stackalloc byte[max];
            var buffer = new Span<byte>(pBuffer, max);

            var result = Utf8Formatter.TryFormat(size, buffer, out var bytesWritten, new StandardFormat('N', 2));
            Debug.Assert(result);
            var str = buffer.Slice(0, bytesWritten);

            i = str.Length - 1;

            while (i > 0 && str[i] == '0')
                i--;

            if (str[i] == '.')
                i--;

            Append(buffer.Slice(0, i + 1));
#endif

            Append(' ');
            Append(units[i]);
        }

        //We don't want to call this "AppendRightPadded" or any other name with
        //another "P" in the word as that often causes intellisense to get messed up
        //and recommend this method over Append (e.g. you type AP)
        public void AppendRight(string s, int padRight, char c = ' ')
        {
            if (s == null)
                return;

            var requiredLength = Math.Max(s.Length, padRight);

            int pos = _pos;
            if (pos > _chars.Length - requiredLength)
            {
                Grow(requiredLength);
            }

            var chars = _chars;

            var target = chars.AsSpan(pos);

            s.AsSpan().CopyTo(target);

            for (var i = s.Length; i < requiredLength; i++)
                target[i] = c;

            _pos += requiredLength;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Append(StringBuilder b)
        {
            int pos = _pos;
            if (pos > _chars.Length - b.Length)
            {
                Grow(b.Length);
            }

            if (_chars != null)
                b.CopyTo(0, _chars, pos, b.Length);
            else
            {
                var chars = _chars;

                for (var i = 0; i < b.Length; i++)
                    chars[pos + i] = b[i];
            }

            _pos += b.Length;
        }

        private void AppendSlow(string s)
        {
            int pos = _pos;
            if (pos > _chars.Length - s.Length)
            {
                Grow(s.Length);
            }

            //Perform s.AsSpan().CopyTo(_chars.AsSpan(pos));
            //without bounds checks
            ref var dst = ref MemoryMarshal.GetReference(_chars.AsSpan());
            ref var src = ref MemoryMarshal.GetReference(s.AsSpan());

            Unsafe.CopyBlockUnaligned(
                ref Unsafe.As<char, byte>(ref Unsafe.Add(ref dst, pos)),
                ref Unsafe.As<char, byte>(ref src),
                (uint) (s.Length * 2)
            );

            _pos += s.Length;
        }

        public void Append(char c, int count)
        {
            if (_pos > _chars.Length - count)
            {
                Grow(count);
            }

            Span<char> dst = _chars.AsSpan(_pos, count);
            for (int i = 0; i < dst.Length; i++)
            {
                dst[i] = c;
            }
            _pos += count;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Append(Utf16String value) => Append(value.AsSpan());

        public void Append(ReadOnlySpan<char> value)
        {
            int pos = _pos;
            if (pos > _chars.Length - value.Length)
            {
                Grow(value.Length);
            }

            value.CopyTo(_chars.AsSpan(_pos));
            _pos += value.Length;
        }

        public void Append(FixedUtf8String value) => Append(value.AsSpan());

        public void Append(FixedUtf16String value) => Append(value.AsSpan());

        public void Append(NullTerminatedString value)
        {
            if (value.Kind == StringKind.UTF16)
                Append(value.AsWideSpan());
            else
                Append(value.AsSpan());
        }

        public unsafe void Append(ReadOnlySpan<byte> value)
        {
            int pos = _pos;
            if (pos > _chars.Length - value.Length)
            {
                Grow(value.Length);
            }

            var dest = _chars;

            for (var i = 0; i < value.Length; i++)
                dest[pos++] = (char) value[i];

            _pos = pos;
        }

        public void Append(ref Utf8StringBuilder builder)
        {
            var value = builder.AsSpan();

            int pos = _pos;
            if (pos > _chars.Length - value.Length)
            {
                Grow(value.Length);
            }

            var dest = _chars;

            for (var i = 0; i < value.Length; i++)
                dest[pos++] = (char) value[i];

            _pos = pos;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Span<char> AppendSpan(int length)
        {
            int origPos = _pos;
            if (origPos > _chars.Length - length)
            {
                Grow(length);
            }

            _pos = origPos + length;
            return _chars.AsSpan(origPos, length);
        }

        public void AppendHex(ulong value, int padRight = 0)
        {
            var numChars = 1;

            var temp = value;

            while ((temp >>= 4) != 0)
                numChars++;

            var pos = _pos;
            var dest = _chars;

            var requiredLength = Math.Max(numChars, padRight);

            if (pos > dest.Length - requiredLength)
            {
                Grow(requiredLength);
                dest = _chars;
            }

            //.NET 5+'s TryFormat is no good because it doesn't tell us how big the resulting string will be, which we need to know
            //to potentially grow the buffer

            //Length prefix 0's
            for (var i = 0; i < padRight - numChars; i++)
                dest[pos++] = '0';

            //Now write the value itself. int.TryFormat to Span<char> is not available in .NET Standard 2.0

            for (var i = numChars - 1; i >= 0; i--)
            {
                var shift = i * 4;
                var val = (value >> shift) & 0xF;

                if (val < 10)
                    dest[pos++] = ((char) ('0' + val));
                else
                    dest[pos++] = ((char) (55 + val)); //'A' will be 65
            }

            _pos = pos;
        }

        //From Iced
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void AppendHex(
            ulong value,
            int digitGroupSize,
            string digitSeparator,
            int digits,
            bool upper,
            bool leadingZero)
        {
            if (digits == 0)
            {
                digits = 1;
                for (ulong tmp = value; ;)
                {
                    tmp >>= 4;
                    if (tmp == 0)
                        break;
                    digits++;
                }
            }

            int hexHigh = upper ? 'A' - 10 : 'a' - 10;
            if (leadingZero && digits < 17 && (int) ((value >> ((digits - 1) << 2)) & 0xF) > 9)
                digits++;// Another 0

            var pos = _pos;
            var dest = _chars;

            var numCharsNeeded = digits;

            if (digitSeparator != null)
                numCharsNeeded += (digits / digitGroupSize) * digitSeparator.Length;

            if (pos > dest.Length - numCharsNeeded)
            {
                Grow(numCharsNeeded);
                dest = _chars;
            }

            bool useDigitSep = digitGroupSize > 0 && !string.IsNullOrEmpty(digitSeparator);
            for (int i = 0; i < digits; i++)
            {
                int index = digits - i - 1;
                int digit = index >= 16 ? 0 : (int) ((value >> (index << 2)) & 0xF);
                if (digit > 9)
                    dest[pos++] = ((char) (digit + hexHigh));
                else
                    dest[pos++] = ((char) (digit + '0'));
                if (useDigitSep && index > 0 && (index % digitGroupSize) == 0)
                {
                    digitSeparator!.AsSpan().CopyTo(dest.AsSpan(pos));
                    pos += digitSeparator!.Length;
                }
            }

            _pos = pos;
        }

        public void AppendEscaped(FixedUtf16String value)
        {
            var index = -1;

            var span = value.AsSpan();

            while ((index = span.IndexOfAny(PooledStringBuilder._escapeCharsUtf16)) != -1)
            {
                //Write all chars up to the escape chars
                if (index == 0)
                {
                    switch (span[0])
                    {
                        case '\n':
                            Append("\\n");
                            break;

                        case '\r':
                            Append("\\r");
                            break;

                        case '\0':
                            Append("\\0");
                            break;

                        case '\t':
                            Append("\\t");
                            break;

                        default:
                            Debug.Assert(false);
                            break;
                    }

                    span = span.Slice(1);
                }
                else
                {
                    Append(span.Slice(0, index));
                    span = span.Slice(index);
                }
            }

            //Append anything remaining
            Append(span);
        }

        public void AppendEscaped(FixedUtf8String value)
        {
            var index = -1;

            var span = value.AsSpan();

            while ((index = span.IndexOfAny(PooledStringBuilder._escapeCharsUtf8)) != -1)
            {
                //Write all chars up to the escape chars
                if (index == 0)
                {
                    switch (span[0])
                    {
                        case (byte) '\n':
                            Append("\\n");
                            break;

                        case (byte) '\r':
                            Append("\\r");
                            break;

                        case (byte) '\0':
                            Append("\\0");
                            break;

                        case (byte) '\t':
                            Append("\\t");
                            break;

                        default:
                            Debug.Assert(false);
                            break;
                    }

                    span = span.Slice(1);
                }
                else
                {
                    Append(span.Slice(0, index));
                    span = span.Slice(index);
                }
            }

            //Append anything remaining
            Append(span);
        }

        public void Replace(char oldChar, char newChar, int startIndex, int count)
        {
            var currentLength = Length;

            if (startIndex > currentLength)
                throw new ArgumentOutOfRangeException();

            if (count < 0 || startIndex > currentLength - count)
                throw new ArgumentOutOfRangeException();

            var chars = _chars;

            for (var i = startIndex; i < startIndex + count; i++)
            {
                if (chars[i] == oldChar)
                    chars[i] = newChar;
            }
        }

        public void Replace(ReadOnlySpan<char> oldValue, ReadOnlySpan<char> newValue, int startIndex, int count)
        {
            var overallSpan = _chars.AsSpan(startIndex, count);

            using var indices = new ValueList<int>();

            var pos = 0;

            while (pos < overallSpan.Length)
            {
                var index = overallSpan.Slice(pos).IndexOf(oldValue);

                if (index == -1)
                    break;

                var matchIndex = pos + index;
                indices.Add(matchIndex);

                pos = matchIndex + oldValue.Length;
            }

            if (indices.Count == 0)
                return;

            if (newValue.Length > oldValue.Length)
            {
                var extraBytesPerItem = newValue.Length - oldValue.Length;
                var numNewChars = extraBytesPerItem * indices.Count;
                var originalLength = Length;
                EnsureCapacity(originalLength + numNewChars);
                _pos += numNewChars;

                var chars = _chars;

                var shiftRemaining = numNewChars;

                for (var i = indices.Count - 1; i >= 0; i--)
                {
                    var valueToReplaceStartIndex = indices[i] + startIndex;
                    var valueToReplaceLength = oldValue.Length;

                    var valueToReplace = chars.AsSpan(valueToReplaceStartIndex, valueToReplaceLength);

                    var contentAfterValueStartIndex = valueToReplaceStartIndex + valueToReplaceLength;
                    var contentAfterValueLength = (i < indices.Count - 1 ? indices[i + 1] : originalLength) - contentAfterValueStartIndex;

                    var contentAfterValue = chars.AsSpan(contentAfterValueStartIndex, contentAfterValueLength);

                    if (contentAfterValueLength > 0)
                    {
                        contentAfterValue.CopyTo(chars.AsSpan(contentAfterValueStartIndex + shiftRemaining));
#if DEBUG
                        //For debugging
                        //contentAfterValue.Clear();
#endif
                    }

                    shiftRemaining -= extraBytesPerItem;
                    var newValueRegion = chars.AsSpan(valueToReplaceStartIndex + shiftRemaining, newValue.Length);
                    newValue.CopyTo(newValueRegion);

#if DEBUG
                    //For debugging
                    //valueToReplace.Clear();
#endif
                    
                }
            }
            else if (newValue.Length == oldValue.Length)
            {
                //Overwrite each occurrence with the new value

                for (var i = 0; i < indices.Count; i++)
                    newValue.CopyTo(overallSpan.Slice(indices[i], newValue.Length));
            }
            else
            {
                //Write the new values directly. We can immediately start by writing the first value over
                //the first match

                var spanToEnd = _chars.AsSpan(startIndex, Length - startIndex);

                var newPos = 0;

                var diff = oldValue.Length - newValue.Length;

                for (var i = 0; i < indices.Count; i++)
                {
                    var index = indices[i];

                    var destPos = index - newPos;

                    newValue.CopyTo(spanToEnd.Slice(destPos, newValue.Length));

                    //Shift everything between this item and the one after it down

                    var gapStart = index + oldValue.Length;
                    var gapEnd = (i < indices.Count - 1 ? indices[i + 1] : spanToEnd.Length);

                    var gapLength = gapEnd - gapStart;

                    if (gapLength > 0)
                        spanToEnd.Slice(gapStart, gapLength).CopyTo(spanToEnd.Slice(destPos + newValue.Length));

                    newPos += diff;
                }

                Length -= diff * indices.Count;
            }
        }

        public void Clear()
        {
            _pos = 0;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private void GrowAndAppend(char c)
        {
            Grow(1);
            Append(c);
        }

        /// <summary>
        /// Resize the internal buffer either by doubling current buffer size or
        /// by adding <paramref name="additionalCapacityBeyondPos"/> to
        /// <see cref="_pos"/> whichever is greater.
        /// </summary>
        /// <param name="additionalCapacityBeyondPos">
        /// Number of chars requested beyond current position.
        /// </param>
        [MethodImpl(MethodImplOptions.NoInlining)]
        private void Grow(int additionalCapacityBeyondPos)
        {
            Debug.Assert(additionalCapacityBeyondPos > 0);
            Debug.Assert(_pos > _chars.Length - additionalCapacityBeyondPos, "Grow called incorrectly, no resize is needed.");

            const uint ArrayMaxLength = 0x7FFFFFC7; // same as Array.MaxLength

            // Increase to at least the required size (_pos + additionalCapacityBeyondPos), but try
            // to double the size if possible, bounding the doubling to not go beyond the max array length.
            int newCapacity = (int) Math.Max(
                (uint) (_pos + additionalCapacityBeyondPos),
                Math.Min((uint) _chars.Length * 2, ArrayMaxLength));

            // Make sure to let Rent throw an exception if the caller has a bug and the desired capacity is negative.
            // This could also go negative if the actual required length wraps around.
            char[] poolArray = ArrayPool<char>.Shared.Rent(newCapacity);

            _chars.AsSpan(0, _pos).CopyTo(poolArray);

            char[] toReturn = _chars;
            _chars = poolArray;
            if (toReturn != null)
            {
                ArrayPool<char>.Shared.Return(toReturn);
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Dispose()
        {
            char[] toReturn = _chars;
            this = default; // for safety, to avoid using pooled array if this instance is erroneously appended to again
            if (toReturn != null)
            {
                ArrayPool<char>.Shared.Return(toReturn);
            }
        }
    }
}
