/*********************************************************************
 * This code was generated by a tool.                                *
 * Please do not modify this file directly - modify Index.tt instead *
 ********************************************************************/

 using System;

namespace PESpy.Ecma335
{
    public readonly struct AssemblyOSIndex
    {
        public readonly int RowId;

        public AssemblyOSIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator AssemblyOSIndex(int value) => new AssemblyOSIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(AssemblyOSIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct AssemblyProcessorIndex
    {
        public readonly int RowId;

        public AssemblyProcessorIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator AssemblyProcessorIndex(int value) => new AssemblyProcessorIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(AssemblyProcessorIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct AssemblyRefOSIndex
    {
        public readonly int RowId;

        public AssemblyRefOSIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator AssemblyRefOSIndex(int value) => new AssemblyRefOSIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(AssemblyRefOSIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct AssemblyRefProcessorIndex
    {
        public readonly int RowId;

        public AssemblyRefProcessorIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator AssemblyRefProcessorIndex(int value) => new AssemblyRefProcessorIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(AssemblyRefProcessorIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct AssemblyRefIndex
    {
        public readonly int RowId;

        public AssemblyRefIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator AssemblyRefIndex(int value) => new AssemblyRefIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(AssemblyRefIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct AssemblyIndex
    {
        public readonly int RowId;

        public AssemblyIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator AssemblyIndex(int value) => new AssemblyIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(AssemblyIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ClassLayoutIndex
    {
        public readonly int RowId;

        public ClassLayoutIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ClassLayoutIndex(int value) => new ClassLayoutIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ClassLayoutIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ConstantIndex
    {
        public readonly int RowId;

        public ConstantIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ConstantIndex(int value) => new ConstantIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ConstantIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct CustomAttributeIndex
    {
        public readonly int RowId;

        public CustomAttributeIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator CustomAttributeIndex(int value) => new CustomAttributeIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(CustomAttributeIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct CustomDebugInformationIndex
    {
        public readonly int RowId;

        public CustomDebugInformationIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator CustomDebugInformationIndex(int value) => new CustomDebugInformationIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(CustomDebugInformationIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct DeclSecurityIndex
    {
        public readonly int RowId;

        public DeclSecurityIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator DeclSecurityIndex(int value) => new DeclSecurityIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(DeclSecurityIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct DocumentIndex
    {
        public readonly int RowId;

        public DocumentIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator DocumentIndex(int value) => new DocumentIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(DocumentIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct EncLogIndex
    {
        public readonly int RowId;

        public EncLogIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator EncLogIndex(int value) => new EncLogIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(EncLogIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct EncMapIndex
    {
        public readonly int RowId;

        public EncMapIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator EncMapIndex(int value) => new EncMapIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(EncMapIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct EventMapIndex
    {
        public readonly int RowId;

        public EventMapIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator EventMapIndex(int value) => new EventMapIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(EventMapIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct EventPtrIndex
    {
        public readonly int RowId;

        public EventPtrIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator EventPtrIndex(int value) => new EventPtrIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(EventPtrIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct EventIndex
    {
        public readonly int RowId;

        public EventIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator EventIndex(int value) => new EventIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(EventIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ExportedTypeIndex
    {
        public readonly int RowId;

        public ExportedTypeIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ExportedTypeIndex(int value) => new ExportedTypeIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ExportedTypeIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct FieldLayoutIndex
    {
        public readonly int RowId;

        public FieldLayoutIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator FieldLayoutIndex(int value) => new FieldLayoutIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(FieldLayoutIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct FieldMarshalIndex
    {
        public readonly int RowId;

        public FieldMarshalIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator FieldMarshalIndex(int value) => new FieldMarshalIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(FieldMarshalIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct FieldPtrIndex
    {
        public readonly int RowId;

        public FieldPtrIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator FieldPtrIndex(int value) => new FieldPtrIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(FieldPtrIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct FieldIndex
    {
        public readonly int RowId;

        public FieldIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator FieldIndex(int value) => new FieldIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(FieldIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct FieldRvaIndex
    {
        public readonly int RowId;

        public FieldRvaIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator FieldRvaIndex(int value) => new FieldRvaIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(FieldRvaIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct FileIndex
    {
        public readonly int RowId;

        public FileIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator FileIndex(int value) => new FileIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(FileIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct GenericParamConstraintIndex
    {
        public readonly int RowId;

        public GenericParamConstraintIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator GenericParamConstraintIndex(int value) => new GenericParamConstraintIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(GenericParamConstraintIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct GenericParamIndex
    {
        public readonly int RowId;

        public GenericParamIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator GenericParamIndex(int value) => new GenericParamIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(GenericParamIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ImplMapIndex
    {
        public readonly int RowId;

        public ImplMapIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ImplMapIndex(int value) => new ImplMapIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ImplMapIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ImportScopeIndex
    {
        public readonly int RowId;

        public ImportScopeIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ImportScopeIndex(int value) => new ImportScopeIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ImportScopeIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct InterfaceImplIndex
    {
        public readonly int RowId;

        public InterfaceImplIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator InterfaceImplIndex(int value) => new InterfaceImplIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(InterfaceImplIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct LocalConstantIndex
    {
        public readonly int RowId;

        public LocalConstantIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator LocalConstantIndex(int value) => new LocalConstantIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(LocalConstantIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct LocalScopeIndex
    {
        public readonly int RowId;

        public LocalScopeIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator LocalScopeIndex(int value) => new LocalScopeIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(LocalScopeIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct LocalVariableIndex
    {
        public readonly int RowId;

        public LocalVariableIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator LocalVariableIndex(int value) => new LocalVariableIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(LocalVariableIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ManifestResourceIndex
    {
        public readonly int RowId;

        public ManifestResourceIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ManifestResourceIndex(int value) => new ManifestResourceIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ManifestResourceIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MemberRefIndex
    {
        public readonly int RowId;

        public MemberRefIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MemberRefIndex(int value) => new MemberRefIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MemberRefIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MethodDebugInformationIndex
    {
        public readonly int RowId;

        public MethodDebugInformationIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MethodDebugInformationIndex(int value) => new MethodDebugInformationIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MethodDebugInformationIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MethodDefIndex
    {
        public readonly int RowId;

        public MethodDefIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MethodDefIndex(int value) => new MethodDefIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MethodDefIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MethodImplIndex
    {
        public readonly int RowId;

        public MethodImplIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MethodImplIndex(int value) => new MethodImplIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MethodImplIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MethodPtrIndex
    {
        public readonly int RowId;

        public MethodPtrIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MethodPtrIndex(int value) => new MethodPtrIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MethodPtrIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MethodSemanticsIndex
    {
        public readonly int RowId;

        public MethodSemanticsIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MethodSemanticsIndex(int value) => new MethodSemanticsIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MethodSemanticsIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct MethodSpecIndex
    {
        public readonly int RowId;

        public MethodSpecIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator MethodSpecIndex(int value) => new MethodSpecIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(MethodSpecIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ModuleRefIndex
    {
        public readonly int RowId;

        public ModuleRefIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ModuleRefIndex(int value) => new ModuleRefIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ModuleRefIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ModuleIndex
    {
        public readonly int RowId;

        public ModuleIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ModuleIndex(int value) => new ModuleIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ModuleIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct NestedClassIndex
    {
        public readonly int RowId;

        public NestedClassIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator NestedClassIndex(int value) => new NestedClassIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(NestedClassIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ParamPtrIndex
    {
        public readonly int RowId;

        public ParamPtrIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ParamPtrIndex(int value) => new ParamPtrIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ParamPtrIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct ParamIndex
    {
        public readonly int RowId;

        public ParamIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator ParamIndex(int value) => new ParamIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(ParamIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct PropertyMapIndex
    {
        public readonly int RowId;

        public PropertyMapIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator PropertyMapIndex(int value) => new PropertyMapIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(PropertyMapIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct PropertyPtrIndex
    {
        public readonly int RowId;

        public PropertyPtrIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator PropertyPtrIndex(int value) => new PropertyPtrIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(PropertyPtrIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct PropertyIndex
    {
        public readonly int RowId;

        public PropertyIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator PropertyIndex(int value) => new PropertyIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(PropertyIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct StandAloneSigIndex
    {
        public readonly int RowId;

        public StandAloneSigIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator StandAloneSigIndex(int value) => new StandAloneSigIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(StandAloneSigIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct StateMachineMethodIndex
    {
        public readonly int RowId;

        public StateMachineMethodIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator StateMachineMethodIndex(int value) => new StateMachineMethodIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(StateMachineMethodIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct TypeDefIndex
    {
        public readonly int RowId;

        public TypeDefIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator TypeDefIndex(int value) => new TypeDefIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(TypeDefIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct TypeRefIndex
    {
        public readonly int RowId;

        public TypeRefIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator TypeRefIndex(int value) => new TypeRefIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(TypeRefIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }

    public readonly struct TypeSpecIndex
    {
        public readonly int RowId;

        public TypeSpecIndex(int rowId)
        {
            RowId = rowId;
        }

        public static explicit operator TypeSpecIndex(int value) => new TypeSpecIndex(value);

        //Can't use implicit operator here, as for some reason this has a backwards effect of allowing other indices to be passed to our tables, due to the presence of a general purpose int indexer
        public static explicit operator int(TypeSpecIndex value) => value.RowId;

        public override string ToString() => RowId.ToString();
    }
}