<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(Build)ClrDebug.props" />
  <!--<Import Project="$(Build)ReFlow.props" />-->

  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\$(TargetFramework)\PESpy\</OutputPath>
    
    <!-- We need this to ensure that our netstandard2.0 folder includes ClrDebug when we create our coreclr folder
         during publish. This also seems to bring in a bunch of other System level DLLs we don't need, but they didn't
         seem to cause an issue in pwsh.exe -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)\$(Configuration)\$(TargetFramework.ToLowerInvariant())\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" />
    <!--<PackageReference Include="Iced" Version="1.21.0" />-->
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PESpy\PESpy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="PESpy.Format.ps1xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PESpy.psd1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PESpy.Types.ps1xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
