<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(Build)ClrDebug.props" />
  <Import Project="$(Build)ReFlow.props" />

  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\SymHelp\src\SymHelp\Symbols\NameMatcher.cs" Link="NameMatcher.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" />
    <PackageReference Include="Iced" Version="1.21.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PESpy\PESpy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="PESpy.psd1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PESpy.Types.ps1xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
