#
# Module manifest for module 'PESpy'
#
# Generated by: lordmilko
#
# Generated on: 11/04/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PESpy.PowerShell.dll'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '651cdb39-d231-47b4-9beb-d812a5c432af'

# Author of this module
Author = 'lordmilko'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2023 lordmilko. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Reverse engineering toolkit for Microsoft compiler generated files'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @('PESpy.PowerShell.dll', 'PESpy.dll')

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('PESpy.Types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('PESpy.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @('*')

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('*')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PSModule', 'PSEdition_Desktop', 'PSEdition_Core', 'pe', 'pdb', 'portable-executable', 'symbols', 'reverse-engineering', 'dotnet', 'metadata')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/lordmilko/PESpy/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/lordmilko/PESpy'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Release Notes: https://github.com/lordmilko/PESpy/releases/tag/v0.1.0

---


PESpy is a C#/PowerShell library for reverse engineering, analyzing and visualizing Microsoft compiler generated file formats.

Given a file, PESpy aims to

* Understand the meaning of *every single byte within that file*
* Support parsing *all known entities*, no matter how obscure
* Minimize abstractions, and mirror native type names wherever possible
* Be highly performant while still being ergonomic. Allocations need be as low as possible!
* Support *all known symbol formats*; COFF, OMF, CodeView, SYM, DBG, PDB files, DNDRB, NB00-NB10, RSDS - if symbols exist, PESpy will read and show them to you
* Unironically provide *information at your fingertips*. The whole entire file hierarchy is exposed via properties; simply open a file, and then poke around in the Locals window
* Support reading PE Files out of a remote debug target where the size of the PE File isn''t known upfront
* Provide tools for performing various file operations, including
    * Detecting file types
    * Locating symbol files (no more `symsrv.dll`!)
    * Resolving RPC Servers
    * Manipulating Symbol Keys
    * Parsing vftables
    * Undecorating symbol names
    * Reading and decompressing files contained in Windows installation media
* Be highly NativeAOT friendly

PESpy is capable of interfacing with many different file types, including PE, PDB, OBJ, DOS, NE, LE, DBG, LIB, OMF OMFLIB, OMFDBG and SYM. For more information, please see the project website.
'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

