<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(Build)ChaosLib.props" />
  <Import Project="$(Build)ClrDebug.props" />
  <Import Project="$(Build)PInvoke.props" />
  <Import Project="$(Build)SymHelp.props" />

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
		<LangVersion>latest</LangVersion>

    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.3" />
    <PackageReference Include="coverlet.collector" Version="3.0.2" />

    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles" Version="1.0.23" ExcludeAssets="compile;runtime" />
    <PackageReference Include="Microsoft.Debugging.Platform.SymSrv" Version="20230731.1609.0" />

    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />

    <!-- SymHelp uses v8 which causes a conflict with .NET 5 which seems to want to use v8 internally -->
    <PackageReference Include="System.Reflection.Metadata" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PESpy.PowerShell\PESpy.PowerShell.csproj" />
    <ProjectReference Include="..\PESpy\PESpy.csproj" />
  </ItemGroup>

  <Target Name="RemoveTestResults" AfterTargets="Build">
    <RemoveDir Directories="..\..\TestResults" />
  </Target>

	<ItemGroup>
		<None Include="$(TraceEventSupportFilesBase)native\x86\msdia140.dll" CopyToOutputDirectory="PreserveNewest" Visible="False" Link="x86\%(FileName)%(Extension)" />
		<None Include="$(TraceEventSupportFilesBase)native\amd64\msdia140.dll" CopyToOutputDirectory="PreserveNewest" Visible="False" Link="x64\%(FileName)%(Extension)" />

		<None Include="$(MicrosoftDebuggingPlatformSymSrvContent)x86\symsrv.dll" CopyToOutputDirectory="PreserveNewest" Visible="False" Link="x86\%(FileName)%(Extension)" />
		<None Include="$(MicrosoftDebuggingPlatformSymSrvContent)amd64\symsrv.dll" CopyToOutputDirectory="PreserveNewest" Visible="False" Link="x64\%(FileName)%(Extension)" />
	</ItemGroup>

</Project>
